"""
American English Dictionary
Contains spelling patterns, vocabulary, and phrases specific to American English
"""

AMERICAN_PATTERNS = {
    'or_vs_our': [
        r'\bcolor\b', r'\bhonor\b', r'\bfavor\b', r'\blabor\b', r'\bhumor\b',
        r'\bneighbor\b', r'\bbehavior\b', r'\bflavor\b', r'\bvalor\b', r'\bvapor\b',
        r'\barbor\b', r'\berror\b', r'\bhorror\b', r'\bmirror\b', r'\bterror\b'
    ],
'er_vs_re': [
        r'\bcenter\b', r'\btheater\b', r'\bmeter\b', r'\bfiber\b', r'\bliter\b',
        r'\btheater\b', r'\bcaliber\b', r'\bcentimeter\b', r'\bkilometer\b', r'\bmillimeter\b'
    ],
'simplified_consonants': [
        r'\btraveling\b', r'\bcanceled\b', r'\bmodeling\b', r'\blabeled\b', r'\btraveler\b',
        r'\bcounselor\b', r'\bjewelry\b', r'\bprograming\b', r'\bquilting\b', r'\bsignaling\b',
        r'\bfueling\b', r'\bmarvelous\b', r'\bappetizer\b'
    ],
'se_vs_ce': [
        r'\bdefense\b', r'\blicense\b', r'\boffense\b', r'\bpretense\b', r'\bvise\b',
        r'\bpractise\b'
    ],
'og_vs_ogue': [
        r'\bcatalog\b', r'\bdialog\b', r'\bmonolog\b', r'\bprolog\b', r'\bepilog\b',
        r'\bdecalog\b', r'\btravelog\b'
    ],
'ze_vs_se': [
        r'\banalyze\b', r'\bcatalyze\b', r'\bparalyze\b', r'\brecognize\b', r'\borganize\b',
        r'\bauthorize\b', r'\bcapitalize\b', r'\bcriticize\b', r'\bemphasize\b', r'\bfinalize\b',
        r'\bharmonize\b', r'\bidealize\b', r'\bimmunize\b', r'\blegalize\b', r'\bmaximize\b',
        r'\bmemorize\b', r'\bminimize\b', r'\bmobilize\b', r'\bnormalize\b', r'\boptimize\b',
        r'\borganize\b', r'\bpopularize\b', r'\brealize\b', r'\brecognize\b', r'\breorganize\b',
        r'\bstabilize\b', r'\bstandardize\b', r'\bsymbolize\b', r'\bsynchronize\b', r'\butilize\b',
        r'\bstigmatize\b', r'\bstigmatizes\b'
    ],
'got_vs_gotten': [
        r'\bgotten\b', r'\bhave gotten\b', r'\bhas gotten\b', r'\bhad gotten\b',
        r'\bwill have gotten\b', r'\bwould have gotten\b', r'\bhave got\b'
    ],
'prepositions': [
        r'\bon a team\b', r'\bon the team\b', r'\bon the weekend\b',
        r'\bdifferent from\b', r'\bdifferent than\b', r'\bprotest something\b'
    ],
    'articles': [
        r'\bin the hospital\b', r'\bin the university\b', r'\bin the school\b',
        r'\bI\'ll see you Monday\b', r'\bSee you Tuesday\b', r'\bI\'ll call you Friday\b',
        r'\bgo to university\b', r'\bgo to hospital\b'
    ],
'collective_nouns': [
        r'\bthe team is\b', r'\bthe government has\b', r'\bthe company is\b',
        r'\bthe family is\b', r'\bthe staff is\b', r'\bthe committee is\b',
        r'\bthe class is\b', r'\bthe board is\b', r'\bthe group is\b',
        r'\bthe audience was\b', r'\bthe band is\b', r'\bthe crew has\b',
        r'\bthe board meets\b', r'\bthe couple has\b', r'\bthe population is\b',
        r'\bthe public is\b', r'\bthe press was\b', r'\bthe team was\b',
        r'\bthe family was\b', r'\bthe committee was\b', r'\bthe company was\b',
        r'\bthe group was\b'
    ],
'everyday_objects': [
        r'\bapartment\b', r'\btruck\b', r'\bcookie\b', r'\belevator\b', r'\bflashlight\b',
        r'\bfries\b', r'\bgas\b', r'\bgasoline\b', r'\bsidewalk\b', r'\bsoccer\b',
        r'\bsweater\b', r'\bchips\b', r'\btrash can\b', r'\bdrugstore\b', r'\bstroller\b',
        r'\bdiaper\b', r'\bfaucet\b', r'\btrunk\b', r'\bhood\b', r'\bmailbox\b',
        r'\beggplant\b', r'\bzucchini\b', r'\bpacifier\b', r'\battorney\b', r'\byard\b',
        r'\bcloset\b', r'\bcomforter\b', r'\bgarbage can\b', r'\boven broiler\b',
        r'\bshopping cart\b', r'\bbaby carriage\b', r'\btennis shoes\b', r'\beraser\b',
        r'\bzipper\b', r'\bscotch tape\b', r'\bcell phone\b', r'\bband-aid\b',
        r'\bvacation\b', r'\bmail\b', r'\bcheck\b', r'\bparking lot\b', r'\bmath\b',
        r'\bunderwear\b', r'\bpants\b', r'\bstore\b', r'\bdorm\b', r'\bdowntown\b',
        r'\bgarbage\b', r'\btrash\b'
    ],
'fashion_fitness': [
        r'\bworking out\b', r'\bplates full\b', r'\bback-to-back meetings\b',
        r'\bdrop big money\b', r'\bsweatpants\b', r'\bsweat-wicking\b',
        r'\bleggings\b', r'\bprinted tanks\b', r'\btank tops\b',
        r'\bchic sneakers\b', r'\bpants\b', r'\bpurses?\b',
        r'\bsweatsuit\b', r'\bpony tail\b', r'\bponytail\b',
        r'\bactive wear\b', r'\bactivewear\b', r'\bathleisure\b',
        r'\bvest\b', r'\bundershirt\b', r'\bfanny pack\b', r'\bhandbags?\b',
        r'\bworkout\b'
    ],
'business_lifestyle': [
        r'\bplates full\b', r'\bback-to-back\b', r'\bdrop big money\b',
        r'\bZoom calls\b', r'\bZoom meetings\b', r'\bworking out\b',
        r'\bgame-changer\b', r'\bregrowth formula\b', r'\bmicroneedling\b',
        r'\bresume\b', r'\binternship\b', r'\bceo\b', r'\blayoff\b',
        r'\bfired\b', r'\braise\b', r'\b401k\b', r'\bhealth insurance\b',
        r'\bpaid time off\b', r'\bsick leave\b', r'\bmaternity leave\b',
        r'\bwork from home\b', r'\bremote work\b', r'\bdiaper\b',
        r'\bstroller\b', r'\bpacifier\b', r'\bfaucet\b', r'\bdrugstore\b',
        r'\bband-aid\b', r'\bq-tip\b', r'\bcotton swab\b', r'\bpaper towel\b',
        r'\bnapkin\b', r'\btissue\b', r'\btoilet paper\b', r'\blaundry\b',
        r'\bwashing machine\b', r'\bdryer\b', r'\bvacuum\b', r'\bmom\b',
        r'\bmommy\b', r'\bgrandma\b', r'\bgrandpa\b', r'\bgreat grandma\b',
        r'\bstay-at-home mom\b', r'\bworking mom\b', r'\bguy\b', r'\bcrush\b',
        r'\bdating\b', r'\bdate\b', r'\bsoulmates?\b', r'\bbest friends?\b',
        r'\broommate\b', r'\bpartner\b', r'\bsoccer\b', r'\bfootball\b',
        r'\bbaseball\b', r'\bsoftball\b', r'\bbasketball\b', r'\bhockey\b',
        r'\bfield\b', r'\bstadium\b', r'\bgym\b', r'\bworkout\b',
        r'\bexercising\b', r'\bfitness\b', r'\bpersonal trainer\b',
        r'\bdoctor\s+apostrophes?\b', r'\bemergency room\b', r'\ber\b',
        r'\bprimary care physician\b', r'\bfamily doctor\b', r'\bpediatrician\b',
        r'\bob-gyn\b', r'\bmedical insurance\b', r'\bprescription\b',
        r'\bover-the-counter\b', r'\bpharmacy\b', r'\bdifferent than\b',
        r'\bvisit with\b', r'\bmeet with\b', r'\btalk with\b',
        r'\bwrite me\b', r'\bcall me\b', r'\btext me\b', r'\bI could care less\b',
        r'\bin the hospital\b', r'\bin the university\b', r'\bin the school\b',
        r'\bgo to the hospital\b', r'\bgo to the university\b', r'\bgo to the school\b',
        r'\bat the hospital\b', r'\bat the university\b', r'\bat the school\b',
        r'\binstagram\b', r'\bfacebook\b', r'\btwitter\b', r'\bx\b',
        r'\btiktok\b', r'\bsnapchat\b', r'\bwhatsapp\b', r'\bzoom\b',
        r'\bDM\b', r'\bdirect message\b', r'\bpost\b', r'\bstory\b', r'\breel\b'
    ],
'vocabulary': [
        r'\bsoccer\b', r'\bgas\b', r'\bmovie theater\b', r'\bmovie theaters\b',
        r'\btheater\b', r'\btheaters\b', r'\bbarracks\b', r'\bmarket\b',
        r'\btaxi\b', r'\btuk-tuk\b', r'\bspices\b',
        r'\bcurry\b', r'\bfried rice\b'
    ],
'idioms': [
        r'\bwhat is your name\b', r'\bplease take necessary action\b',
        r'\bout of town\b', r'\bpostpone\b', r'\breschedule\b',
        r'\bthank you\b', r'\bplease reply\b', r'\bsatisfactory\b',
        r'\bmy namesake\b', r'\bcousin\b'
    ],
'common_phrases': [
        r'\bwhat is your name\b', r'\bwhat is your full name\b',
        r'\bwhere are you from\b', r'\bwhere do you live\b',
        r'\bwhat city are you from\b', r'\bhow are you\b',
        r'\bhow are you doing\b', r'\bhow\'s it going\b',
        r'\bwhat\'s up\b', r'\bthank you\b', r'\bthanks\b',
        r'\byou\'re welcome\b', r'\bno problem\b', r'\bno worries\b',
        r'\bmy pleasure\b', r'\bwelcome\b', r'\bplease\b',
        r'\bthis morning\b', r'\btonight\b', r'\blast night\b',
        r'\bday before yesterday\b', r'\bday after tomorrow\b',
        r'\bin the morning\b', r'\bin the afternoon\b', r'\bin the evening\b',
        r'\bat night\b', r'\bat noon\b', r'\bat midnight\b',
        r'\bhalf past eight\b', r'\bquarter to\b', r'\bquarter past\b',
        r'\bwhat time is it\b', r'\bo\'clock\b', r'\bI\'m going\b',
        r'\bI\'m coming\b', r'\bI\'ll be there\b', r'\bI\'m from\b',
        r'\bwhat can I do\b', r'\bwhat can you do\b', r'\bwhat to say\b',
        r'\bbye\b', r'\bgoodbye\b', r'\bsee you\b', r'\bsee you later\b',
        r'\bhave lunch\b', r'\bhave dinner\b', r'\bdid you eat\b',
        r'\bhave you eaten\b', r'\bhad your meal\b', r'\bI just ate\b',
        r'\bI just finished\b', r'\bjust now\b', r'\bhe just left\b',
        r'\bout of town\b', r'\baway\b', r'\bon vacation\b', r'\bon leave\b',
        r'\bsick day\b', r'\bsick leave\b', r'\bannual leave\b',
        r'\bmaternity leave\b', r'\bpaternity leave\b', r'\bhalf day\b',
        r'\boffer letter\b', r'\bemployment letter\b', r'\bpromotion letter\b',
        r'\bwhat is your educational background\b', r'\bwhat is your degree\b',
        r'\bwhat did you study\b', r'\bI graduated in 2010\b',
        r'\bI graduated from\b', r'\bI got my degree in\b', r'\bI studied at\b',
        r'\bmy major\b', r'\bmy minor\b', r'\bboard exam\b',
        r'\bstandardized test\b', r'\bSAT\b', r'\bACT\b', r'\bGRE\b', r'\bGMAT\b',
        r'\bcollege life\b', r'\bdorm life\b', r'\bprivate university\b',
        r'\bpublic university\b', r'\bstate school\b', r'\bivy league\b',
        r'\bcommunity college\b', r'\bmedical school\b', r'\blaw school\b',
        r'\bcousin\b', r'\bfirst cousin\b', r'\bsecond cousin\b',
        r'\bbrother-in-law\b', r'\bsister-in-law\b', r'\bmother-in-law\b',
        r'\bfather-in-law\b', r'\bson-in-law\b', r'\bdaughter-in-law\b',
        r'\buncle\b', r'\baunt\b', r'\bmy father is\b', r'\bmy mother is\b',
        r'\bonly child\b', r'\boldest brother\b', r'\bolder brother\b',
        r'\byoungest brother\b', r'\byounger brother\b', r'\boldest sister\b',
        r'\bolder sister\b', r'\byoungest sister\b', r'\byounger sister\b',
        r'\bmy parents\b', r'\bmy grandparents\b', r'\blive with family\b',
        r'\bnuclear family\b', r'\bextended family\b', r'\barranged marriage\b',
        r'\blove marriage\b', r'\bmarriage proposal\b', r'\bproposal\b',
        r'\bpop the question\b', r'\bget engaged\b', r'\bengagement\b',
        r'\bengagement party\b', r'\bwedding\b', r'\bwedding ceremony\b',
        r'\bwedding reception\b', r'\bwhite wedding\b', r'\bdestination wedding\b',
        r'\bhoneymoon\b', r'\bwedding vows\b', r'\bwedding ring\b',
        r'\bbride\b', r'\bgroom\b', r'\bmaid of honor\b', r'\bbest man\b',
        r'\bbridesmaid\b', r'\bgroomsman\b', r'\bflower girl\b', r'\bring bearer\b',
        r'\bnewly married\b', r'\bnewlyweds\b', r'\bMerry Christmas\b',
        r'\bHappy New Year\b', r'\bHappy Thanksgiving\b', r'\bHappy Easter\b',
        r'\bHappy Halloween\b', r'\bHappy birthday\b', r'\bHappy anniversary\b',
        r'\bChristmas\b', r'\bChristmas Eve\b', r'\bChristmas Day\b',
        r'\bNew Year\'s Eve\b', r'\bNew Year\'s Day\b', r'\bThanksgiving\b',
        r'\bFourth of July\b', r'\bIndependence Day\b', r'\bMemorial Day\b',
        r'\bLabor Day\b', r'\bMartin Luther King Day\b', r'\bPresidents Day\b',
        r'\bValentine\'s Day\b', r'\bMother\'s Day\b', r'\bFather\'s Day\b',
        r'\bHalloween\b', r'\bEaster\b', r'\bRamadan\b', r'\bEid\b', r'\bDiwali\b',
        r'\bnew dress\b', r'\bnew outfit\b', r'\bhave you eaten\b',
        r'\bdid you eat\b', r'\bwhat did you have\b', r'\bwhat did you eat\b',
        r'\bI had rice\b', r'\bI had fish\b', r'\bI had steak\b', r'\bI had chicken\b',
        r'\bbiryani\b', r'\bcurry\b', r'\brice and beans\b', r'\bfish and chips\b',
        r'\bmashed potatoes\b', r'\bfried chicken\b', r'\bpotato chips\b',
        r'\bfries\b', r'\btea\b', r'\bcup of tea\b', r'\biced tea\b',
        r'\bcoffee\b', r'\bcup of coffee\b', r'\blatte\b', r'\bcappuccino\b',
        r'\bespresso\b', r'\bsamosa\b', r'\bhow much\b', r'\bhow much is it\b',
        r'\bwhat does it cost\b', r'\bwhat\'s the price\b', r'\bprice is high\b',
        r'\bit\'s expensive\b', r'\btoo expensive\b', r'\btoo pricey\b',
        r'\bit costs an arm and a leg\b', r'\bcan you give me a discount\b',
        r'\bis there a discount\b', r'\bany discounts\b', r'\bstudent discount\b',
        r'\bsenior discount\b', r'\bsale\b', r'\bon sale\b', r'\bclearance\b',
        r'\bbargaining\b', r'\bhaggling\b', r'\bthat\'s too much\b',
        r'\bmy final offer\b', r'\bwhat\'s your best price\b', r'\bweigh it\b',
        r'\bcan you weigh it\b', r'\bhalf pound\b', r'\bone pound\b',
        r'\bone kilo\b', r'\btwo hundred grams\b', r'\bper pound\b',
        r'\bper ounce\b', r'\bper piece\b', r'\bwholesale price\b',
        r'\bretail price\b', r'\bto go\b', r'\btake out\b', r'\btakeaway\b',
        r'\bcan you pack it\b', r'\bcan you box it up\b', r'\bout of town\b',
        r'\bgoing home\b', r'\bheading home\b', r'\bhometown\b', r'\bhome state\b',
        r'\bdowntown\b', r'\bticket booking\b', r'\badvance ticket\b',
        r'\badvance purchase\b', r'\bwill-call\b', r'\be-ticket\b',
        r'\bonline ticket\b', r'\bmobile ticket\b', r'\bbus stop\b',
        r'\bferry terminal\b', r'\btrain station\b', r'\bairport\b',
        r'\bboarding\b', r'\bboarding time\b', r'\bhow long is the trip\b',
        r'\bhow many hours\b', r'\btravel time\b', r'\bjourney time\b',
        r'\bI booked a ticket\b', r'\bwaiting list\b', r'\bstandby\b',
        r'\bconfirmed reservation\b', r'\bI\'m not feeling well\b',
        r'\bI feel sick\b', r'\bI feel under the weather\b', r'\bI have a fever\b',
        r'\bcold and cough\b', r'\bheadache\b', r'\bstomach ache\b',
        r'\bstomach pain\b', r'\bdiarrhea\b', r'\btyphoid\b',
        r'\bdoctor\'s office\b', r'\bclinic\b', r'\bpharmacy\b', r'\bdrugstore\b',
        r'\blab\b', r'\bdiagnostic lab\b', r'\btest results\b', r'\bblood test\b',
        r'\bx-ray\b', r'\bEKG\b', r'\bECG\b', r'\bultrasound\b',
        r'\bblood pressure\b', r'\bBP\b', r'\bblood sugar\b', r'\bglucose test\b',
        r'\bmedicine\b', r'\bmedication\b', r'\btake your medicine\b',
        r'\bdid you take your medicine\b', r'\bon time\b', r'\bas prescribed\b',
        r'\bfollow-up\b', r'\bfollow-up appointment\b', r'\bcheck-up\b',
        r'\bphysical\b', r'\bit\'s hot\b', r'\bhot weather\b', r'\bheat wave\b',
        r'\bsummer\b', r'\brainy season\b', r'\brainy\b', r'\bheavy rain\b',
        r'\bcloudy\b', r'\bovercast\b', r'\bstorm\b', r'\bthunderstorm\b',
        r'\bhurricane\b', r'\btyphoon\b', r'\btornado\b', r'\bthunder\b',
        r'\blightning\b', r'\bnice weather\b', r'\bpleasant weather\b',
        r'\bcold weather\b', r'\bwinter\b', r'\bcold snap\b', r'\bcold spell\b',
        r'\bair pollution\b', r'\bcold wave\b', r'\bcold front\b', r'\bdrought\b',
        r'\bflood\b', r'\bflooding\b', r'\bup to par\b', r'\bnot up to par\b',
        r'\bnot up to scratch\b', r'\bby hook or by crook\b',
        r'\bby leaps and bounds\b', r'\bfrom time to time\b',
        r'\bevery now and then\b', r'\bonce in a while\b', r'\bnowadays\b',
        r'\bthese days\b', r'\bin current times\b', r'\bat present\b',
        r'\bcurrently\b', r'\bas per\b', r'\baccording to\b', r'\bto my knowledge\b',
        r'\bin my opinion\b', r'\bfrom my perspective\b', r'\bmy point of view\b',
        r'\bwith all due respect\b', r'\bwith respect\b', r'\bmore or less\b',
        r'\bwhat can I do\b', r'\bwhat can be done\b', r'\bit is what it is\b',
        r'\bthat\'s the thing\b', r'\bthat\'s the point\b', r'\bthe thing is\b',
        r'\bthe fact is\b', r'\bactually\b', r'\bto be honest\b', r'\bhonestly\b',
        r'\bfrankly\b', r'\bfrankly speaking\b', r'\bgenerally\b',
        r'\bgenerally speaking\b', r'\btruth be told\b', r'\bI\'m telling you\b',
        r'\byou know\b', r'\byou see\b', r'\bokay\b', r'\bok\b', r'\bOK\b',
        r'\bfine\b', r'\bthat\'s fine\b', r'\bnot bad\b', r'\bso-so\b',
        r'\bI see\b', r'\bgot it\b', r'\bunderstood\b', r'\byes, I know\b',
        r'\bno, I don\'t know\b', r'\bmaybe\b', r'\bperhaps\b', r'\bpossibly\b',
        r'\bnot possible\b', r'\bimpossible\b', r'\bno problem\b', r'\bno issue\b',
        r'\bno worries\b', r'\bdon\'t worry about it\b', r'\byou\'re welcome\b',
        r'\bwelcome\b', r'\bit\'s okay\b',
        r'\bnever mind\b', r'\bdoesn\'t matter\b', r'\bwhat a beautiful\b',
        r'\bwhat a nice\b', r'\bwhat a shame\b', r'\bwhat a pity\b',
        r'\bwhat a waste\b', r'\bhow nice\b', r'\bvery good\b', r'\bvery bad\b',
        r'\boh my god\b', r'\bOMG\b', r'\boh my\b', r'\boh my goodness\b',
        r'\bwow\b', r'\bunbelievable\b', r'\bincredible\b', r'\bmind-blowing\b',
        r'\bout of this world\b', r'\bawesome\b', r'\bfantastic\b', r'\btremendous\b',
        r'\bstrike\b', r'\bprotest\b', r'\bdemonstration\b', r'\bmarch\b',
        r'\brally\b', r'\blockade\b', r'\bsiege\b', r'\bsit-in\b',
        r'\btown hall\b', r'\btown hall meeting\b', r'\bpublic meeting\b',
        r'\bpolitical rally\b', r'\belection platform\b', r'\bparty platform\b',
        r'\bvoter fraud\b', r'\belection irregularities\b', r'\binterim government\b',
        r'\btransitional government\b', r'\bfreedom fighter\b', r'\bveteran\b',
        r'\bwar\b', r'\bWorld War II\b', r'\bVietnam War\b', r'\b9/11\b',
        r'\bdigital age\b', r'\binformation age\b', r'\bsexual harassment\b',
        r'\b#MeToo\b', r'\bfatwa\b', r'\bhate crime\b', r'\bdomestic violence\b',
        r'\bdowry\b', r'\bbride burning\b', r'\bhonor killing\b', r'\bchild marriage\b',
        r'\boppression\b', r'\bviolence against women\b', r'\bhuman trafficking\b',
        r'\bchild labor\b', r'\bclimate change\b', r'\bclimate refugee\b',
        r'\bRohingya\b', r'\bdisplaced persons\b', r'\bdisplaced people\b',
        r'\brefugees\b', r'\basylum seekers\b', r'\bmobile recharge\b',
        r'\bVenmo\b', r'\bPayPal\b', r'\bZelle\b', r'\bmobile banking\b',
        r'\bonline banking\b', r'\bsend money\b', r'\bcash out\b',
        r'\bphone number\b', r'\bcell number\b', r'\bSIM card\b', r'\bdata plan\b',
        r'\binternet plan\b', r'\bFacebook\b', r'\bFB\b', r'\bFacebook page\b',
        r'\bFacebook group\b', r'\bstatus update\b', r'\bstatus\b', r'\bpost\b',
        r'\bshare\b', r'\blike\b', r'\blikes\b', r'\bcomment\b', r'\bDM\b',
        r'\bdirect message\b', r'\bMessenger\b', r'\bWhatsApp\b', r'\bFaceTime\b',
        r'\bSkype\b', r'\bZoom\b', r'\bGoogle Meet\b', r'\bTeams\b',
        r'\bMicrosoft Teams\b', r'\bonline class\b', r'\bvirtual class\b',
        r'\bZoom class\b', r'\bin this regard\b', r'\bin this connection\b',
        r'\bin this context\b', r'\bwith reference to\b', r'\bwith regard to\b',
        r'\bwith respect to\b', r'\bregarding\b', r'\bconcerning\b',
        r'\bas regards\b', r'\bin reply to\b', r'\bin response to\b',
        r'\bI would like to\b', r'\bI wish to\b', r'\bI want to\b',
        r'\bI intend to\b', r'\bI propose to\b', r'\bI suggest that\b',
        r'\bI recommend that\b', r'\bplease\b', r'\bI would appreciate it if\b',
        r'\bI would be grateful if\b', r'\bfor your attention\b',
        r'\bfor your consideration\b', r'\bfor your information\b', r'\bFYI\b',
        r'\bfor your reference\b', r'\bplease see attached\b',
        r'\battached please find\b', r'\bplease find attached\b',
        r'\bsee attached\b', r'\brefer to the attached\b', r'\bmore than\b',
        r'\bover\b', r'\bless than\b', r'\bunder\b', r'\babout\b', r'\baround\b',
        r'\bapproximately\b', r'\bmaximum\b', r'\bmax\b', r'\bminimum\b',
        r'\bmin\b', r'\bat least\b', r'\bat most\b', r'\ba lot\b', r'\blots\b',
        r'\ba whole lot\b', r'\bmany\b', r'\bso many\b', r'\btoo many\b',
        r'\btoo much\b', r'\bquite a lot\b', r'\bfew\b', r'\ba few\b',
        r'\blittle\b', r'\ba little\b', r'\bquite a few\b', r'\bmost\b',
        r'\bthe majority\b', r'\bmost of the time\b', r'\bmost people\b',
        r'\bin most cases\b', r'\bin some cases\b', r'\bin many cases\b',
        r'\bvery\b', r'\bso\b', r'\btoo\b', r'\bvery much\b', r'\bso much\b',
        r'\breally\b', r'\bquite\b', r'\bpractically\b', r'\bbasically\b',
        r'\bactually\b', r'\bliterally\b', r'\bseriously\b', r'\bdead serious\b',
        r'\bcompletely\b', r'\btotally\b', r'\babsolutely\b', r'\bentirely\b',
        r'\bfully\b', r'\bas\s+\w+\s+as\b', r'\bthe same as\b',
        r'\bdifferent from\b', r'\bdifferent than\b', r'\bsimilar to\b',
        r'\blike\b', r'\bsuch as\b', r'\bfor example\b', r'\be\.g\.\b',
        r'\bfor instance\b', r'\bet cetera\b', r'\betc\.\b', r'\bcan\b',
        r'\bbe able to\b', r'\bwill be able to\b', r'\bhave to\b',
        r'\bhas to\b', r'\bhad to\b', r'\bmust\b', r'\bneed to\b',
        r'\bneeds to\b', r'\bneeded to\b', r'\bshould\b', r'\bwould have to\b',
        r'\bmight have to\b'
        r'\bcandy\b',  # US; UK sweets
        r'\bsneakers\b',  # US; UK trainers
        r'\bbathroom\b',  # US; UK toilet/loo (also restroom)
        r'\brestroom\b',
        r'\bliquor store\b',  # US; UK off-licence
        r'\btrunk\b',  # car (US); UK boot (you have trunk as tree?)
        r'\bhood\b',  # car (US); UK bonnet
        r'\bgarbage\b', r'\btrash\b',  # US; UK rubbish
        r'\bfall\b',  # US autumn (you have only 'fall' as verb)
    ],
'verb_tenses': [
        r'\bI just ate\b', r'\bI just finished\b', r'\bI just saw\b',
        r'\bI just came\b', r'\bI just went\b', r'\bI just did\b',
        r'\bI just left\b', r'\bI just arrived\b', r'\bI just called\b',
        r'\bHe just left\b', r'\bShe just came\b', r'\bThey just arrived\b',
        r'\bI already ate\b', r'\bI already finished\b', r'\bI already saw\b',
        r'\bI already did\b', r'\bI already went\b', r'\bI already came\b',
        r'\bDid you eat yet\?\b', r'\bDid you finish yet\?\b',
        r'\bDid you call yet\?\b', r'\bDid you go yet\?\b',
        r'\bI never saw that\b', r'\bI never did that\b',
        r'\bI never went there\b', r'\bI never ate that\b',
        r'\bDid you ever go\b', r'\bDid you ever see\b',
        r'\bDid you ever try\b', r'\bDid you ever eat\b',
        r'\bI have just eaten\b', r'\bI have just finished\b',
        r'\bI have just seen\b', r'\bI have just come\b',
        r'\bI have been here since morning\b',
        r'\bI have been waiting for two hours\b',
        r'\bI have known him for five years\b',
        r'\bI have lived here since 2010\b',
        r'\bI had done it before he came\b',
        r'\bI had finished when he arrived\b',
        r'\bI had already eaten when he called\b',
        r'\bI will have finished by tomorrow\b',
        r'\bI will have completed it before you come\b',
        r'\bIf I had known\b', r'\bIf I had seen\b',
        r'\bIf I had gone\b', r'\bIf I had tried\b',
        r'\bI wouldn\'t have gone\b', r'\bI would have gone\b',
        r'\bHe wouldn\'t have come\b', r'\bHe would have come\b',
        r'\bI didn\'t go until he came\b',
        r'\bI won\'t leave until you come\b',
        r'\bIt has been two years since I met him\b',
        r'\bNo sooner did I arrive than he left\b',
        r'\bHardly had I arrived when he called\b',
        r'\bAs soon as I arrived, he left\b',
        r'\bWhile I was going, I met him\b',
        r'\bWhen I was coming, I saw her\b',
        r'\bBy the time I arrived, he had left\b',
        r'\bAfter I finished, I went home\b',
        r'\bBefore I left, I called him\b',
        r'\bSince I met you, my life has changed\b',
        r'\bI had already finished when he came\b',
        r'\bI had never seen such a thing\b',
        r'\bI am going tomorrow\b', r'\bHe is coming next week\b',
        r'\bThey are arriving tonight\b', r'\bWe are starting next month\b',
        r'\bWhen I was young, I would play baseball\b',
        r'\bI used to play football\b', r'\bHe used to live here\b',
        r'\bYou had better go\b', r'\bYou\'d better go\b',
        r'\bHe had better leave\b', r'\bHe\'d better leave\b',
        r'\bI would rather stay\b', r'\bI\'d rather stay\b',
        r'\bHe would rather go\b', r'\bHe\'d rather go\b',
        r'\bHe talks as if he knew everything\b',
        r'\bIt is time we left\b', r'\bIt\'s time we left\b',
        r'\bI wish I knew\b', r'\bI wish I were there\b',
        r'\bIf only I knew\b', r'\bThe work was done by me\b',
        r'\bThe letter was sent by him\b', r'\bI got the work done\b',
        r'\bHe had his car repaired\b', r'\bShe got her hair cut\b',
        r'\bHe kept on talking\b', r'\bShe kept on working\b',
        r'\bHe went on talking\b', r'\bHe stopped smoking\b',
        r'\bHe stopped to smoke\b', r'\bI remember meeting him\b',
        r'\bI remembered to meet him\b', r'\bI tried calling\b',
        r'\bI tried to call\b', r'\bThis means changing plans\b',
        r'\bI meant to change plans\b', r'\bI regret saying that\b',
        r'\bI regret to inform you\b', r'\bI am afraid of flying\b',
        r'\bI am afraid to fly\b', r'\bI am interested in learning\b',
        r'\bI am interested to learn\b', r'\bHe said that he would come\b',
        r'\bShe told me that she was coming\b', r'\bHe asked me what my name was\b',
        r'\bHe told me to go\b', r'\bShe ordered me to leave\b',
        r'\bLet\'s go\b', r'\bLet\'s eat\b', r'\bLet\'s start\b',
        r'\bLet me go\b', r'\bLet him try\b', r'\bMake him understand\b',
        r'\bMake her see\b', r'\bHave it done\b', r'\bHave it checked\b',
        r'\bGet it done\b', r'\bGet it fixed\b', r'\bIt needs cleaning\b',
        r'\bIt needs to be cleaned\b', r'\bI want it done\b',
        r'\bI want it finished\b', r'\bI saw him coming\b',
        r'\bI saw him come\b', r'\bHelp me do it\b',
        r'\bHelp me to do it\b', r'\bPrevent him from going\b',
        r'\bStop her from leaving\b', r'\bHe insisted on going\b',
        r'\bShe insisted on coming\b', r'\bHe apologized for being late\b',
        r'\bThank you for coming\b', r'\bThank you for helping\b',
        r'\bI look forward to meeting you\b',
        r'\bWe look forward to hearing from you\b', r'\bI used to smoke\b',
        r'\bI am used to smoking\b', r'\bI am about to leave\b',
        r'\bHe is about to start\b', r'\bI am going to go\b',
        r'\bI will go\b', r'\bI shall go\b', r'\bWe shall see\b',
        r'\bMay I come in\?\b', r'\bMay I ask something\?\b',
        r'\bI might come\b', r'\bHe might be late\b', r'\bI can do it\b',
        r'\bCan I go\?\b', r'\bCould you help\?\b',
        r'\bCould I borrow this\?\b', r'\bYou should go\b',
        r'\bWe should help\b', r'\bYou must go\b', r'\bWe must help\b',
        r'\bI have to go\b', r'\bHe has to leave\b', r'\bI need to go\b',
        r'\bYou need to understand\b', r'\bYou ought to help\b',
        r'\bWe ought to respect our elders\b', r'\bI prefer to stay\b',
        r'\bI prefer staying\b', r'\bI like to read\b', r'\bI like reading\b',
        r'\bI love to travel\b', r'\bI love travelling\b',
        r'\bI hate to wait\b', r'\bI hate waiting\b', r'\bI started to work\b',
        r'\bI started working\b', r'\bI began to understand\b',
        r'\bI began understanding\b', r'\bI continued to work\b',
        r'\bI continued working\b'
    ],
'new_american_terms': [
        r'\bair fryer\b', r'\bair frying\b', r'\bathleisure\b',
        r'\bbackbencher\b', r'\bblotting paper\b', r'\bbiodata\b',
        r'\bchatbot\b', r'\bclinical intervention\b', r'\bdeep frying\b',
        r'\bdigital behavior\b', r'\bdopamine hit\b', r'\bdopamine receptors\b',
        r'\bempty calories\b', r'\bfashionista\b', r'\bgamophobic\b',
        r'\bglycemic control\b', r'\bglycogen stores\b', r'\bGPA-5\b',
        r'\bgut health\b', r'\bhigh maintenance\b', r'\bhyperinsulinemia\b',
        r'\biftar trap\b', r'\binsulin sensitization\b', r'\bjumpstarts\b',
        r'\bkitten heels\b', r'\bloungewear\b', r'\bmetabolic switch\b',
        r'\bmicroneedling\b', r'\bmonounsaturated fatty acids\b',
        r'\bneuromuscular control\b', r'\bno strings attached\b',
        r'\bnucleus accumbens\b', r'\bpicky eating\b', r'\bplatform heels\b',
        r'\bpookie\b', r'\bpre-diabetic\b', r'\bready-made garment\b',
        r'\bregenerative medicine\b', r'\bsetting spray\b', r'\bsugar addiction\b',
        r'\bsugar spike\b', r'\bsugar thermostat\b', r'\bsweat-wicking\b',
        r'\bsystem override\b', r'\bT-zone\b', r'\btoddler parent\b',
        r'\bwaterproof\b', r'\bweight gain\b', r'\bzombie cells\b',
        r'\bZoom calls\b'
    ],
'legal': [
    r'\battorney\b', r'\bcounselor\b', r'\besquire\b',
    r'\bstand your ground\b', r'\bplead the fifth\b',
    r'\bSocial Security\b', r'\bMedicaid\b', r'\bMedicare\b',
    r'\bW-2\b', r'\b1099\b', r'\b401(k)\b'  # you have 401k
    ],
'colloquial': [
    r'\bso\b',              # US "So, I was like..."
    r'\blike\b',            # filler word
    r'\byou know\b',
    r'\bI mean\b',
    r'\banyways\b',         # US informal; UK "anyway"
    r'\bgonna\b', r'\bwanna\b', r'\bgotta\b'
    ],
'prepositions': [
    r'\bmeet with someone\b',   # US; UK "meet someone"
    r'\btalk with\b',           # US; UK "talk to"
    r'\bvisit with\b',          # US (chat); UK "visit" (no with)
    r'\bstop by\b', r'\bstop in\b',  # US casual
    r'\bwrite someone\b',       # US no 'to'
    ],
'dates': [
    r'\b\w+ \d{1,2}, \d{4}\b',  # April 5, 2024 (US order)
    r'\b\d{1,2}/\d{1,2}/\d{2,4}\b',  # 4/5/24 (month/day)
    r'\b(?:january|february|...)\s+\d{1,2}\b',  # no 'th' (UK: 5th April)
    ],
'time': [
    r'\b(?:10|11|12)\s*(?:a\.m\.|p\.m\.|am|pm)\b',  # 10am (no 'in the morning')
    r'\bquarter after\b', r'\bquarter of\b',  # US: "quarter of five" = 4:45
    ],
'punctuation': [
    r'"double quotes" for speech',   # US prefers double quotes; UK single
    r'Mr\.', r'Mrs\.', r'Ms\.', r'Dr\.',  # US includes period
    r'write me\b',      # US: "write me" vs UK "write to me"
    r'called me\b',     # US: "called me" (no 'to')
],
}