"""
Bangladeshi English Dictionary
Contains spelling patterns, vocabulary, idioms, and cultural terms specific to Bangladeshi English
"""

BANGLADESHI_PATTERNS = {
    'or_vs_our': [
        r'\bcolour\b', r'\bhonour\b', r'\bfavour\b', r'\blabour\b', r'\bhumour\b',
        r'\bneighbour\b', r'\bbehaviour\b', r'\bflavour\b', r'\bvalour\b', r'\bvapour\b',
        r'\barbour\b', r'\berror\b', r'\bhorror\b', r'\bmirror\b', r'\bterror\b',
        r'\bcolur\b', r'\bhonur\b', r'\bfavur\b', r'\bneigbour\b'
    ],
    'er_vs_re': [
        r'\bcentre\b', r'\btheatre\b', r'\bmetre\b', r'\bfibre\b', r'\blitre\b',
        r'\bcalibre\b', r'\bcentimetre\b', r'\bkilometre\b', r'\bmillimetre\b'
    ],
    'simplified_consonants': [
        r'\btravelling\b', r'\bcancelled\b', r'\bmodelling\b', r'\blabelled\b', r'\btraveller\b',
        r'\bcounsellor\b', r'\bjewellery\b', r'\bprogramming\b', r'\bquilting\b', r'\bsignalling\b',
        r'\bfuelling\b', r'\bmarvellous\b', r'\bappetiser\b'
    ],
    'se_vs_ce': [
        r'\bdefence\b', r'\blicence\b', r'\boffence\b', r'\bpretence\b', r'\bvice\b',
        r'\bpractise\b', r'\bpractice\b', r'\blicense\b', r'\bdefense\b',
        r'\bpretense\b', r'\bl licence\b', r'\blicensing\b', r'\bpractice paper\b',
        r'\bpractise questions\b'
    ],
    'og_vs_ogue': [
        r'\bcatalogue\b', r'\bdialogue\b', r'\bmonologue\b', r'\bprologue\b', r'\bepilogue\b',
        r'\bdecalogue\b', r'\btravelogue\b', r'\bcatalogues\b', r'\bonline catalogue\b'
    ],
    'ze_vs_se': [
        r'\banalyse\b', r'\borganise\b', r'\brecognise\b', r'\brealise\b', r'\bemphasise\b',
        r'\bcriticise\b', r'\bmaximise\b', r'\bminimise\b', r'\butilise\b', r'\bfinalise\b',
        r'\bauthorise\b', r'\bcapitalise\b', r'\bharmonise\b', r'\bidealise\b', r'\bimmunise\b',
        r'\blegalise\b', r'\bmobilise\b', r'\bnormalise\b', r'\bpopularise\b', r'\bstabilise\b',
        r'\bstandardise\b', r'\bsymbolise\b', r'\bsynchronise\b', r'\bstigmatise\b',
        r'\bcriticize\b', r'\bparalyse\b', r'\bcatalyse\b', r'\borganisation\b',
        r'\brealisation\b', r'\brealize\b', r'\borganize\b', r'\brecognize\b'
    ],
# Add to 'or_vs_our' or new 'phonetic_spellings' category
'phonetic_spellings': [
    r'\bvegitables\b', r'\bvejetables\b',  # vegetables
    r'\bgoverment\b', r'\bgovernmnet\b',   # government
    r'\bunversity\b', r'\bunivercity\b',   # university
    r'\bcomission\b', r'\bcommision\b',    # commission
    r'\bacheive\b', r'\beventually\b',     # achieve/eventually (vowel confusion)
    r'\bwomens\b', r'\bchilds\b',          # overregularized plurals
    r'\bscissor\b', r'\bnews\b are\b',     # count/mass noun confusion
    r'\bissuez\b', r'\bkameezs\b',
    r'\bbhisha\b',        # "visa" misspelled phonetically
    r'\bfree reign\b',    # should be "free rein"
    r'\bthingsin\b',      # run-on word: "things in"
    r'\bperusing\b',      # caution: often confused with "pursuing" in BD English
    r'\bpurple sheds\b',           # should be "purple shades"
    r'\bfine tunes\b'             # should be "fine-tunes"
    r'\boff-springs\b',   # should be "offspring"
    r'\boffsprings\b',    # without hyphen
    ],
'reduplication': [
    r'\bchai-chai\b', r'\bchai\s+chai\b',      # tea etc.
    r'\bkhabar-dabar\b', r'\bfood-dood\b',      # food and stuff
    r'\bghor-shor\b', r'\bhouse\s+work\s+etc\b',
    r'\bthaka-kotha\b', r'\btalk\s+talk\b',
    r'\bkitaba-ditaba\b', r'\bbooks\s+etc\b',
    r'\bjawa-asa\b', r'\bgoing\s+coming\b', r'\bsong and dance\b'
    ],
'discourse_markers': [
    r'\bisn\'t it\?\b', r'\bwasn\'t it\?\b',   # universal tag (vs UK variation)
    r'\bno\?\b', r'\bright\?\b',
    r'\bactually\b', r'\bbasically\b',         # overused fillers
    r'\byou know\b', r'\byou see\b',
    r'\bthat means\b', r'\bmeaning\b',
    r'\bso to say\b', r'\bas if\b',
    r'\bkind of\b', r'\bsort of\b', r'\bmight we add\b',
    r'\bmatter is\b',
    r'\bfact is\b',
    r'\b thing is\b',
    r'\bpoint is\b',
    r'\bto tell truth\b',
    r'\bas a matter of fact\b',
    r'\babove everything\b'
    ],
'syntax': [
    r'\bwhat\s+you\s+want\?\b',               # missing copula
    r'\bwhy\s+you\s+going\?\b',
    r'\bhow\s+you\s+know\?\b',
    r'\bmuch\s+people\b',                     # "much" with countable
    r'\bevery\s+things\b',                    # "everything" split
    r'\btwo\s+three\s+days\b',                # approximate numbers
    r'\bten\s+to\s+fifteen\s+minutes\b',
    r'\bon top your game\b',  r'\bfalling prey into\b',
    r'\bstuff dreams are made of\b', r'\bdone and dusted with\b',
    r'\bseem look\b',              # double verb error
    r'\ba handful of \w+ has\b',   # subject-verb agreement
    r'\b(?:is|was) her another\b' # article order error
    ],
'intensifiers': [
    r'\btoo\s+much\s+costly\b',               # double intensifier
    r'\bvery\s+much\s+good\b',
    r'\bso\s+much\s+hot\b',
    r'\bquite\s+good\s+enough\b',
    r'\benough\s+good\b', # "good enough" inverted
    r'\bso much the\b',  # "so much the better" structure
    r'\btoo much costly\b',  # double intensifier (found in ad criticism)
    r'\bvery much good\b',  # common pattern

    ],
'code_switching': [
    r'\bkhub\s+good\b', r'\bvery\s+bhalo\b',
    r'\bthik\s+ache\b', r'\bokay\s+ache\b',
    r'\bbreak\s+khabo\b', r'\btea\s+khaben\b',
    r'\bstudy\s+korbo\b', r'\bwork\s+korchi\b',
    r'\bbhalo\s+lagche\b', r'\bvalo\s+lags\b',
    r'\bcha khaben\b',
    r'\bbreak khabo\b',
    r'\bstudy korbo\b', r'\bbiye\b',
    r'\bdeshi\b', r'\bdadubari\b',  # grandfather's village home
    r'\bkaashbon\b',               # Kash flower field
    r'\bshiuly\b',                 # Shiuli flower
    r'\bshiuli\b',                 # alternative spelling
    r'\btuntuni\b',       # tailorbird / small decorative light
    r'\bmach ranga\b',    # kingfisher
    r'\bmachranga\b',     # alternative spelling
    ],
'honorifics': [
    r'\bSir\b', r'\bMadam\b', r'\bMa\'am\b',
    r'\bBhai\b', r'\bBrother\b',              # used as title
    r'\bApa\b', r'\bSister\b',
    r'\bUncle\b', r'\bAunty\b',               # for elders (non-relative)
    r'\bSir\s+[A-Z]', r'\bMr\.\s+Sir\b',     # double honorific
    r'\bFufu\b',             #  paternal aunt
    r'\bFufi\b'
    ],
'institutional': [
    r'\bBCS\b', r'\bPSC\b', r'\bBPSC\b',     # Public Service Commission
    r'\bNTRCA\b',                             # Non-govt teachers registration
    r'\bBTRC\b',                              # telecom regulator
    r'\bBSEC\b',                              # securities exchange
    r'\bNBR\b',                               # National Board of Revenue
    r'\bBIDA\b',                              # investment authority
    r'\bBEZA\b', r'\bBEPZA\b',               # economic zones
    r'\bBIFT\b',                   # BGMEA Institute of Fashion and Technology
    r'\bBGMEA\b',                  # Bangladesh Garment Manufacturers and Exporters Association
    ],
'numbering': [
        r'\b\d+\s*lakh\b', r'\b\d+\s*lakhs\b', r'\blakh\b', r'\blakhs\b',
        r'\b\d+\s*crore\b', r'\b\d+\s*crores\b', r'\bcrore\b', r'\bcrores\b',
        r'\b\d+\s*half\s*kilo\b', r'\bhalf\s*kilo\b', r'\b\d+\s*kilo\b',
        r'\bmaund\b', r'\bseer\b', r'\btola\b', r'\bquarter kilo\b'
    ],
    'currency': [
        r'\btk\.?\s*\d+', r'\bTk\.?\s*\d+', r'\btaka\b', r'\bTK\b', r'\btk\b',
        r'\bTk\s*\d+[k]?\b', r'\btk\s*\d+[k]?\b', r'\bTk\d+[k]?\b', r'\btk\d+[k]?\b',
        r'\bpoisha\b'
    ],
    'education_term': [
        r'\bprimary school\b', r'\bprimary education\b', r'\bhigh school\b',
        r'\bsecondary school\b', r'\bcollege\b', r'\bdegree college\b',
        r'\buniversity\b', r'\bmedical college\b', r'\bengineering college\b',
        r'\btextile college\b', r'\bpolytechnic\b', r'\bmadrasa\b', r'\bmadrasah\b',
        r'\balia madrasa\b', r'\bdakhil madrasa\b', r'\balim madrasa\b',
        r'\bfazil madrasa\b', r'\bkamil madrasa\b', r'\bPSC\b', r'\bJSC\b',
        r'\bJDC\b', r'\bSSC\b', r'\bDakhil\b', r'\bHSC\b', r'\bAlim\b',
        r'\bHonours\b', r'\bMasters\b', r'\bFazil\b', r'\bKamil\b', r'\bCGPA\b',
        r'\bSGPA\b', r'\bletter grade\b', r'\bgrade point\b', r'\bmarks\b',
        r'\bnumbers\b', r'\bdivision\b', r'\bclass\b', r'\bstars\b',
        r'\bscholarship\b', r'\btalent pool scholarship\b', r'\bgeneral scholarship\b',
        r'\bboard scholarship\b', r'\beducation board\b', r'\bboard exam\b',
        r'\bboard roll\b', r'\bregistration no\b', r'\bEIIN\b', r'\bMPO\b',
        r'\bMPO listed\b', r'\bnon-MPO\b', r'\bsemester\b', r'\bterm\b',
        r'\byear\b', r'\bfirst year\b', r'\bsecond year\b', r'\bthird year\b',
        r'\bfourth year\b', r'\bfinal year\b', r'\bfinal year project\b',
        r'\bthesis\b', r'\bassignment\b', r'\bproject work\b', r'\bfield work\b',
        r'\bviva\b', r'\bviva voce\b', r'\bpractical exam\b', r'\bpractical\b',
        r'\blab report\b', r'\badmission test\b', r'\badmission circular\b',
        r'\badmission form\b', r'\bunit\b', r'\bunit-wise\b', r'\bmerit list\b',
        r'\bwaiting list\b', r'\bquota\b', r'\bfreedom fighter quota\b',
        r'\btribal quota\b', r'\bdistrict quota\b', r'\bDhaka University admission test\b',
        r'\bBUET admission\b', r'\bmajor\b', r'\bsubject\b', r'\bhonours subject\b',
        r'\boptional subject\b', r'\bcompulsory subject\b', r'\belective subject\b',
        r'\b4th subject\b', r'\bcombination\b', r'\bDU\b', r'\bJU\b', r'\bRU\b',
        r'\bCU\b', r'\bBUET\b', r'\bSUST\b', r'\bKU\b', r'\bDUET\b', r'\bNSU\b',
        r'\bBRACU\b', r'\bIUT\b', r'\bnational university\b', r'\bNU\b',
        r'\bopen university\b', r'\bBOU\b', r'\bheadmaster\b', r'\bheadmistress\b',
        r'\bprincipal\b', r'\blecturer\b', r'\bdemonstrator\b', r'\binstructor\b',
        r'\bsuper\b', r'\bcoach\b', r'\bprivate tutor\b', r'\bstudent\b',
        r'\bfresher\b', r'\bvarsity student\b', r'\bcollegian\b', r'\bboarder\b',
        r'\bday scholar\b', r'\bhostelite\b', r'\bhall student\b', r'\bresidential student\b',
        r'\bexternal student\b', r'\bprivate candidate\b', r'\bregular student\b',
        r'\birregular student\b', r'\bhall\b', r'\bhostel\b', r'\bcommon room\b',
        r'\bteacher\'s room\b', r'\blibrary\b', r'\breading room\b', r'\blab\b',
        r'\blaboratory\b', r'\bauditorium\b', r'\bplayground\b', r'\bcanteen\b',
        r'\bcoaching center\b', r'\bcoaching\b', r'\btranscript\b', r'\bmark sheet\b',
        r'\bcertificate\b', r'\btestimonial\b', r'\bcharacter certificate\b',
        r'\bprovisional certificate\b', r'\bdegree certificate\b', r'\bregistration card\b',
        r'\bID card\b', r'\badmit card\b', r'\broll number\b', r'\bregistration number\b',
        r'\bprivate university\b', r'\bpublic university\b', r'\bnational university affiliated college\b',
        r'\bunder national university\b', r'\bdegree pass course\b', r'\bdegree honours course\b',
        r'\bmasters preliminary\b', r'\bmasters final\b', r'\bMPHIL\b', r'\bPhD\b',
        r'\bpost graduate\b', r'\bunder graduate\b', r'\bHSC equivalent\b',
        r'\bSSC equivalent\b', r'\btechnical education board\b', r'\bmadrasa education board\b',
        r'\bgeneral education board\b', r'\bGPA 5\b', r'\bA\+\b', r'\bgolden A\+\b',
        r'\bstar marks\b', r'\bgrace marks\b', r'\bimprovement exam\b',
        r'\bimprovement candidate\b', r'\brecheck\b', r'\bscrutiny\b', r'\bretake\b',
        r'\bbacklog\b', r'\bsupplementary exam\b', r'\bgrad grub\b'
    ],
    'transportation': [
        r'\bhighway\b', r'\bnational highway\b', r'\bregional highway\b', r'\bRHD road\b',
        r'\bZila road\b', r'\bUpazila road\b', r'\bUnion road\b', r'\bvillage road\b',
        r'\bgrameen rasta\b', r'\bmetalled road\b', r'\bpaved road\b', r'\bpucca road\b',
        r'\bunmetalled road\b', r'\bunpaved road\b', r'\bkutcha road\b', r'\bbypass\b',
        r'\bring road\b', r'\bflyover\b', r'\boverpass\b', r'\bunderpass\b', r'\bbridge\b',
        r'\bsetubandh\b', r'\bculvert\b', r'\bJamuna Bridge\b', r'\bBangabandhu Bridge\b',
        r'\bPadma Bridge\b', r'\bMeghna Bridge\b', r'\bRupsha Bridge\b', r'\bKarnaphuli Tunnel\b',
        r'\broad\b', r'\bshahor rasta\b', r'\bstreet\b', r'\blane\b', r'\bgoli\b',
        r'\bmain road\b', r'\bby-lane\b', r'\bbylane\b', r'\bfootpath\b', r'\bpavement\b',
        r'\bfoot overbridge\b', r'\bzebra crossing\b', r'\bpedestrian crossing\b',
        r'\btraffic signal\b', r'\btraffic light\b', r'\btraffic sign\b', r'\broad sign\b',
        r'\broundabout\b', r'\bcircle\b', r'\bmor\b', r'\bchowrasta\b', r'\btrisection\b',
        r'\btri-mor\b', r'\bbus bay\b', r'\bbus stop\b', r'\bbus stand\b', r'\btruck stand\b',
        r'\blorry stand\b', r'\btaxi stand\b', r'\bCNG stand\b', r'\brickshaw stand\b',
        r'\bparking\b', r'\bparking area\b', r'\bparking lot\b', r'\bcar park\b',
        r'\bmulti-storey parking\b', r'\bparking garage\b', r'\bbus\b', r'\bpublic bus\b',
        r'\bprivate bus\b', r'\bmini-bus\b', r'\bminibus\b', r'\bmicro-bus\b', r'\bmicrobus\b',
        r'\bhuman hauler\b', r'\bBRTC bus\b', r'\blocal bus\b', r'\blong-distance bus\b',
        r'\bnight coach\b', r'\bnight bus\b', r'\bAC bus\b', r'\bnon-AC bus\b',
        r'\bbus counter\b', r'\bbus depot\b', r'\bGreen Line\b', r'\bHanif Enterprise\b',
        r'\bShyamoli Paribahan\b', r'\bEna Transport\b', r'\bSR Travels\b', r'\bSoudia Coach\b',
        r'\bCNG\b', r'\bCNG auto-rickshaw\b', r'\bauto-rickshaw\b', r'\bautorickshaw\b',
        r'\btempo\b', r'\blempo\b', r'\brickshaw\b', r'\brickshaw van\b', r'\bvan rickshaw\b',
        r'\bbaby taxi\b', r'\btomtom\b', r'\beasy bike\b', r'\bauto-tempo\b', r'\blegged van\b',
        r'\brickshaw puller\b', r'\bCNG driver\b', r'\btempo driver\b', r'\btaxi\b',
        r'\btaxi cab\b', r'\byellow taxi\b', r'\bUber\b', r'\bPathao\b', r'\bShohoz\b',
        r'\bObhai\b', r'\bride-sharing\b', r'\bbike taxi\b', r'\bmotorcycle taxi\b',
        r'\bcar rental\b', r'\bcar\b', r'\bgari\b', r'\bprivate car\b', r'\bmicrobus\b',
        r'\bjeep\b', r'\bSUV\b', r'\bsports utility vehicle\b', r'\bsedan\b', r'\bhatchback\b',
        r'\bToyota\b', r'\bToyota Axio\b', r'\bToyota Allion\b', r'\bToyota Premio\b',
        r'\bMitsubishi\b', r'\bMitsubishi Pajero\b', r'\bNissan\b', r'\bNissan X-Trail\b',
        r'\bHonda\b', r'\bHonda Civic\b', r'\bHyundai\b', r'\bHyundai Elantra\b', r'\bKia\b',
        r'\bChevrolet\b', r'\bProton\b', r'\bPerodua\b', r'\bMaruti\b', r'\bSuzuki\b',
        r'\bTata\b', r'\bMahindra\b', r'\bAshok Leyland\b', r'\bWalton\b', r'\bbike\b',
        r'\bmotorbike\b', r'\bmotorcycle\b', r'\bscooter\b', r'\bYamaha\b', r'\bHonda\b',
        r'\bSuzuki\b', r'\bBajaj\b', r'\bTVS\b', r'\bHero\b', r'\bRunner\b', r'\bAtlas\b',
        r'\bhelmet\b', r'\bcrash helmet\b', r'\btruck\b', r'\blorry\b', r'\bcovered van\b',
        r'\btruck lorry\b', r'\bcontainer truck\b', r'\btrailer\b', r'\btrailer truck\b',
        r'\bdump truck\b', r'\btanker\b', r'\boil tanker\b', r'\btruck driver\b',
        r'\blorry driver\b', r'\bhelper\b', r'\blaunch\b', r'\blaunch terminal\b',
        r'\blaunch ghat\b', r'\bferry\b', r'\bferry ghat\b', r'\bro-ro ferry\b',
        r'\bsteamer\b', r'\brocket steamer\b', r'\bboat\b', r'\bnouka\b', r'\btrawler\b',
        r'\bspeedboat\b', r'\bengine boat\b', r'\bcountry boat\b', r'\bsampan\b',
        r'\bdinghy\b', r'\bkewra boat\b', r'\bbalam boat\b', r'\bwater taxi\b',
        r'\bwater bus\b', r'\bBIWTC\b', r'\bBIWTA\b', r'\briver route\b', r'\binland waterway\b',
        r'\bSadarghat\b', r'\bPaturia Ghat\b', r'\bAricha Ghat\b', r'\bChandpur Launch Terminal\b',
        r'\bBarisal Launch Terminal\b', r'\bKhulna Launch Terminal\b', r'\btrain\b',
        r'\brailway\b', r'\brail line\b', r'\brailway station\b', r'\breil station\b',
        r'\bKamalapur Railway Station\b', r'\bAirport Railway Station\b',
        r'\bCantonment Railway Station\b', r'\bBangabandhu Bridge East/West Station\b',
        r'\bintercity train\b', r'\blocal train\b', r'\bcommuter train\b', r'\bsuburban train\b',
        r'\bmetro rail\b', r'\bMRT\b', r'\bDhaka Metro Rail\b', r'\bMRT Line-6\b',
        r'\bcommuter rail\b', r'\bDEMU train\b', r'\bEMU train\b', r'\bparabat train\b',
        r'\bsubarna express\b', r'\btista express\b', r'\bekota express\b', r'\bmohanagar express\b',
        r'\bturnaround train\b', r'\bmail train\b', r'\bpassenger train\b', r'\bgoods train\b',
        r'\bfreight train\b', r'\brake\b', r'\brailway bridge\b', r'\brailway crossing\b',
        r'\blevel crossing\b', r'\bticket counter\b', r'\bticket collector\b', r'\bTC\b',
        r'\bticket checker\b', r'\brailway police\b', r'\bGRP\b', r'\bBR\b', r'\bBangladesh Railway\b',
        r'\bbroad gauge\b', r'\bmeter gauge\b', r'\bdual gauge\b', r'\bsleeper class\b',
        r'\bchair class\b', r'\bAC class\b', r'\bAC berth\b', r'\bnon-AC berth\b',
        r'\bShovon chair\b', r'\bShovon\b', r'\bSulob\b', r'\bAC seat\b', r'\bAC cabin\b',
        r'\bairport\b', r'\bHazrat Shahjalal International Airport\b', r'\bHSIA\b',
        r'\bShah Amanat International Airport\b', r'\bOsmani International Airport\b',
        r'\bCox\'s Bazar Airport\b', r'\bJessore Airport\b', r'\bRajshahi Airport\b',
        r'\bSaidpur Airport\b', r'\bBarisal Airport\b', r'\bdometic airport\b',
        r'\binternational airport\b', r'\bflight\b', r'\bdomestic flight\b',
        r'\binternational flight\b', r'\bdirect flight\b', r'\bconnecting flight\b',
        r'\btransit flight\b', r'\bBiman\b', r'\bBiman Bangladesh Airlines\b',
        r'\bUS-Bangla Airlines\b', r'\bNovoair\b', r'\bRegent Airways\b', r'\bairline ticket\b',
        r'\bairfare\b', r'\bboarding pass\b', r'\bcheck-in counter\b', r'\bimmigration\b',
        r'\bcustoms\b', r'\bvisa on arrival\b', r'\bterminal\b', r'\bbus terminal\b',
        r'\bGabtoli Bus Terminal\b', r'\bMohakhali Bus Terminal\b', r'\bSayedabad Bus Terminal\b',
        r'\bKallyanpur Bus Stand\b', r'\bAbdullahpur Bus Stand\b', r'\bUttara Bus Stand\b',
        r'\bJatrabari Bus Stand\b', r'\bferry terminal\b', r'\bghat\b', r'\bcontainer depot\b',
        r'\bICD\b', r'\bPangaon Inland Container Terminal\b', r'\bKamalapur ICD\b',
        r'\bDhaka Inland Container Depot\b', r'\bChittagong Port\b', r'\bMongla Port\b',
        r'\bPayra Port\b', r'\bBenapole Land Port\b', r'\bBurimari Land Port\b', r'\bHili Land Port\b',
        r'\bSonamasjid Land Port\b', r'\bAkhaura Land Port\b', r'\bBRTA\b',
        r'\bBangladesh Road Transport Authority\b', r'\bBRTC\b', r'\bBangladesh Road Transport Corporation\b',
        r'\bRHD\b', r'\bRoads and Highways Department\b', r'\bLGED\b', r'\bLocal Government Engineering Department\b',
        r'\bDTCB\b', r'\bDhaka Transport Coordination Board\b', r'\bSTP\b', r'\bStrategic Transport Plan\b',
        r'\bDPHE\b', r'\bRAJUK\b', r'\bDNCC\b', r'\bDhaka North City Corporation\b', r'\bDSCC\b',
        r'\bDhaka South City Corporation\b', r'\bCCC\b', r'\bChittagong City Corporation\b',
        r'\bvehicle registration\b', r'\bregistration number\b', r'\bDhaka Metro\b',
        r'\bChittagong Metro\b', r'\bRajshahi Metro\b', r'\bKhulna Metro\b', r'\bBarisal Metro\b',
        r'\bSylhet Metro\b', r'\bfitness certificate\b', r'\btax token\b', r'\brouting permit\b',
        r'\broute permit\b', r'\bdriver\'s license\b', r'\bdriving license\b', r'\blearner\'s license\b',
        r'\bprofessional driver\'s license\b', r'\btraffic rules\b', r'\btraffic law\b',
        r'\btraffic violation\b', r'\btraffic fine\b', r'\bchallan\b', r'\btraffic jam\b',
        r'\bgridlock\b', r'\brush hour\b', r'\bpeak hour\b', r'\boff-peak\b', r'\btraffic police\b',
        r'\btraffic sergeant\b', r'\btraffic inspector\b', r'\bpolice checkpoint\b', r'\bcheck post\b',
        r'\bbarricade\b', r'\bDMP Traffic\b', r'\bCMP Traffic\b', r'\btraffic control room\b',
        r'\btraffic CCTV\b', r'\bpothole\b', r'\bkhana khondok\b', r'\bwaterlogging\b',
        r'\broadside waterlogging\b', r'\bconstruction work\b', r'\bdiverted\b', r'\bdetour\b',
        r'\broad blockage\b', r'\bprocession\b', r'\bhartal\b', r'\broad accident\b',
        r'\baccident\b', r'\bcrash\b', r'\bcollision\b', r'\bhead-on collision\b',
        r'\brear-end collision\b', r'\bhit-and-run\b', r'\bover-speeding\b', r'\brace\b',
        r'\bhelmetless driving\b', r'\bengine\b', r'\bclutch\b', r'\bgear\b', r'\bgear box\b',
        r'\bbreak\b', r'\bbreak system\b', r'\baccelerator\b', r'\bsteering\b', r'\bwheel\b',
        r'\btyre\b', r'\btire\b', r'\btube\b', r'\btyre puncture\b', r'\bpuncture shop\b',
        r'\bbattery\b', r'\bheadlight\b', r'\bheadlamp\b', r'\btaillight\b', r'\bindicator\b',
        r'\bblinker\b', r'\bhorn\b', r'\bwindshield\b', r'\bwindscreen\b', r'\bwiper\b',
        r'\bmirror\b', r'\bside mirror\b', r'\brearview mirror\b', r'\bbonnet\b', r'\bhood\b',
        r'\bboot\b', r'\btrunk\b', r'\bchassis\b', r'\bmuffler\b', r'\bsilencer\b',
        r'\bexhaust\b', r'\bradiator\b', r'\bcar service\b', r'\btuning\b', r'\boil change\b',
        r'\bgrease\b', r'\blubricant\b', r'\bpetrol\b', r'\bgasoline\b', r'\boctane\b',
        r'\bpremium petrol\b', r'\bdiesel\b', r'\bCNG\b', r'\bauto gas\b', r'\bfuel station\b',
        r'\bpetrol pump\b', r'\bgas station\b', r'\bfilling station\b', r'\bCNG station\b',
        r'\bauto gas station\b', r'\bgarage\b', r'\bmechanic\b', r'\bmistri\b', r'\bworkshop\b',
        r'\btire shop\b', r'\btyre shop\b', r'\bcar wash\b', r'\bregistration certificate\b',
        r'\bregistration book\b', r'\bbook\b', r'\btax token\b', r'\bfitness certificate\b',
        r'\broute permit\b', r'\binsurance certificate\b', r'\binsurance paper\b',
        r'\bgreen book\b', r'\bblue book\b', r'\bdriver\b', r'\bbus driver\b',
        r'\btruck driver\b', r'\blorry driver\b', r'\btaxi driver\b', r'\bCNG driver\b',
        r'\brickshaw puller\b', r'\bvan puller\b', r'\bhelper\b', r'\bsupervisor\b',
        r'\bconductor\b', r'\bticket checker\b', r'\bTC\b', r'\bstation master\b',
        r'\bloco master\b', r'\btrain driver\b', r'\bengine driver\b', r'\bguard\b',
        r'\bpilot\b', r'\bmajor\b', r'\bserang\b', r'\bkhalasi\b', r'\blaunch staff\b',
        r'\bdeck hand\b', r'\bkilometre\b', r'\bkm\b', r'\bmile\b', r'\byard\b',
        r'\bfeet\b', r'\bmeter\b', r'\bmetre\b', r'\bhour journey\b', r'\bminute drive\b',
        r'\bhow far\b', r'\bdistance\b', r'\btravel time\b', r'\bbook ticket\b',
        r'\badvance ticket\b', r'\bonline ticket\b', r'\bSMS ticket\b', r'\bcounter ticket\b',
        r'\bfirst class\b', r'\bbusiness class\b', r'\beconomy class\b', r'\bchair class\b',
        r'\bberth\b', r'\bseat\b', r'\bwindow seat\b', r'\baisle seat\b', r'\blower berth\b',
        r'\bupper berth\b', r'\bwaiting list\b', r'\bWL\b', r'\bRAC\b', r'\bconfirmed ticket\b',
        r'\bcancelled ticket\b', r'\brefund\b', r'\bcancellation charge\b', r'\bfare\b',
        r'\bticket fare\b', r'\bchild fare\b', r'\badult fare\b', r'\bsenior citizen fare\b',
        r'\bstudent concession\b', r'\bfamily fare\b', r'\bgroup fare\b', r'\btransport strike\b',
        r'\bbus strike\b', r'\blaunch strike\b', r'\btrain strike\b', r'\bhartal\b',
        r'\broad blockade\b', r'\btransport worker strike\b', r'\bowner-driver dispute\b',
        r'\bfare hike\b', r'\bticket price hike\b', r'\bdiesel price hike\b', r'\boil price increase\b',
        r'\bCNG price increase\b', r'\bfare fix\b', r'\bovercharging\b', r'\bextra fare\b',
        r'\btout\b', r'\bticket black market\b', r'\bovercrowding\b', r'\boverloading\b',
        r'\bovercapacity\b', r'\bstanding passenger\b', r'\bstanding capacity\b'
    ],
    'law_government': [
        r'\bconstitution\b', r'\bconstitutional amendment\b',
        r'\bconstitutional provision\b', r'\bfundamental rights\b', r'\bdirective principles\b',
        r'\bconstitutional remedy\b', r'\bwrit petition\b', r'\bwrit jurisdiction\b',
        r'\bwrit of habeas corpus\b', r'\bwrit of mandamus\b', r'\bwrit of prohibition\b',
        r'\bwrit of certiorari\b', r'\bwrit of quo warranto\b', r'\bjudicial review\b',
        r'\bseparation of powers\b', r'\brule of law\b', r'\bJatiya Sangsad\b',
        r'\bNational Parliament\b', r'\bSangsad\b', r'\bparliament\b', r'\bMP\b',
        r'\bMember of Parliament\b', r'\bSpeaker\b', r'\bDeputy Speaker\b',
        r'\bLeader of House\b', r'\bLeader of Opposition\b', r'\bChief Whip\b',
        r'\bWhip\b', r'\bParliamentary Secretary\b', r'\bState Minister\b',
        r'\bDeputy Minister\b', r'\bParliamentary Standing Committee\b', r'\bselect committee\b',
        r'\bparliamentary session\b', r'\bbudget session\b', r'\bquestion hour\b',
        r'\bzero hour\b', r'\badjournment motion\b', r'\bcalling attention motion\b',
        r'\bnoconfidence motion\b', r'\bvote of confidence\b', r'\bvote of no-confidence\b',
        r'\btrust vote\b', r'\bdivision vote\b', r'\bvoice vote\b', r'\bparliamentary debate\b',
        r'\bproceedings\b', r'\bvotes and proceedings\b', r'\bgazette notification\b',
        r'\bofficial gazette\b', r'\bBangladesh Gazette\b', r'\blegislative assembly\b',
        r'\bconstituent assembly\b', r'\bconstituency\b', r'\bseat\b',
        r'\bparliamentary constituency\b', r'\bEC\b', r'\bElection Commission\b',
        r'\bCEC\b', r'\bChief Election Commissioner\b', r'\bElection Commissioner\b',
        r'\belection manifesto\b', r'\bpolling station\b', r'\bvoting center\b',
        r'\bpresiding officer\b', r'\bpolling officer\b', r'\bvoter list\b',
        r'\belectoral roll\b', r'\bvoter ID card\b', r'\bnational ID card\b', r'\bNID\b',
        r'\bsmart card\b', r'\bvoter turnout\b', r'\bvalid votes\b', r'\binvalid votes\b',
        r'\brejected votes\b', r'\belectoral code of conduct\b', r'\belection observers\b',
        r'\belection monitoring\b', r'\belection petition\b', r'\belection tribunal\b',
        r'\bby-election\b', r'\bby-poll\b', r'\bgeneral election\b', r'\bnational election\b',
        r'\blocal government election\b', r'\bupazila election\b', r'\bunion parishad election\b',
        r'\bcity corporation election\b', r'\bpourashava election\b', r'\bvote rigging\b',
        r'\belection irregularities\b', r'\bballot paper\b', r'\bballot box\b', r'\bEVM\b',
        r'\belectronic voting machine\b', r'\bgovernment\b', r'\bshorkar\b', r'\bcaretaker government\b',
        r'\bCTG\b', r'\binterim government\b', r'\badviser\b', r'\badvisors council\b',
        r'\bcabinet\b', r'\bcabinet division\b', r'\bcabinet meeting\b', r'\bcabinet secretary\b',
        r'\bPrime Minister\b', r'\bPM\b', r'\bPMO\b', r'\bPrime Minister\'s Office\b',
        r'\bChief Adviser\b', r'\bPresident\b', r'\bBangabhaban\b', r'\bministry\b',
        r'\bminister\b', r'\bCabinet Minister\b', r'\bState Minister\b', r'\bDeputy Minister\b',
        r'\bAdviser\b', r'\bMinistry of Home Affairs\b', r'\bMinistry of Law, Justice and Parliamentary Affairs\b',
        r'\bMinistry of Finance\b', r'\bMinistry of Foreign Affairs\b', r'\bMinistry of Public Administration\b',
        r'\bMinistry of Education\b', r'\bMinistry of Health\b', r'\bsecretary\b',
        r'\badditional secretary\b', r'\bjoint secretary\b', r'\bdeputy secretary\b',
        r'\bsenior assistant secretary\b', r'\bassistant secretary\b', r'\blocal government\b',
        r'\bUP\b', r'\bUnion Parishad\b', r'\bunion council\b', r'\bUP chairman\b',
        r'\bUnion Parishad chairman\b', r'\bUP member\b', r'\bunion member\b', r'\bUP secretary\b',
        r'\bUP complex\b', r'\bUP auditorium\b', r'\bUP office\b', r'\bupazila\b', r'\bupazilla\b',
        r'\bupazila parishad\b', r'\bupazila chairman\b', r'\bupazila nirbahi officer\b', r'\bUNO\b',
        r'\bupazila complex\b', r'\bupazila health complex\b', r'\bupazila education officer\b',
        r'\bupazila agriculture officer\b', r'\bzila\b', r'\bdistrict\b', r'\bzila parishad\b',
        r'\bdistrict council\b', r'\bdeputy commissioner\b', r'\bDC\b', r'\bdistrict magistrate\b',
        r'\bDM\b', r'\badditional deputy commissioner\b', r'\bsenior assistant commissioner\b',
        r'\bassistant commissioner\b', r'\bAC Land\b', r'\bAC General\b', r'\bcircle office\b',
        r'\bthanar\b', r'\bthana\b', r'\bthana parishad\b', r'\bcity corporation\b', r'\bmayor\b',
        r'\bcouncilor\b', r'\bcouncillor\b', r'\bward councilor\b', r'\bward commissioner\b',
        r'\bpourashava\b', r'\bpourasabha\b', r'\bmunicipality\b', r'\bpourashava mayor\b',
        r'\bpourashava councilor\b', r'\bpaurosava\b', r'\bSupreme Court\b', r'\bHigh Court Division\b',
        r'\bHCD\b', r'\bAppellate Division\b', r'\bAD\b', r'\bChief Justice\b', r'\bCJ\b',
        r'\bJustice\b', r'\bJudge\b', r'\bChief Justice of Bangladesh\b', r'\bAttorney General\b',
        r'\bAG\b', r'\bAdditional Attorney General\b', r'\bDeputy Attorney General\b',
        r'\bAssistant Attorney General\b', r'\bSupreme Court Bar Association\b', r'\bDistrict Court\b',
        r'\bDistrict Judge\b', r'\bDJ\b', r'\bAdditional District Judge\b', r'\bJoint District Judge\b',
        r'\bSenior Assistant Judge\b', r'\bAssistant Judge\b', r'\bMetropolitan Sessions Judge\b',
        r'\bMetropolitan Magistrate\b', r'\bChief Metropolitan Magistrate\b', r'\bCMM\b',
        r'\bMagistrate\b', r'\bExecutive Magistrate\b', r'\bJudicial Magistrate\b',
        r'\bChief Judicial Magistrate\b', r'\bCJM\b', r'\bCourt of Settlement\b', r'\bFamily Court\b',
        r'\bArtha Rin Adalat\b', r'\bMoney Loan Court\b', r'\bNari O Shishu Nirjatan Daman Tribunal\b',
        r'\bWomen and Children Tribunal\b', r'\bCyber Tribunal\b', r'\bEnvironment Court\b',
        r'\bLabour Court\b', r'\bAdministrative Tribunal\b', r'\bIncome Tax Appellate Tribunal\b',
        r'\bCustoms Appellate Tribunal\b', r'\bVAT Appellate Tribunal\b', r'\bLand Survey Tribunal\b',
        r'\bSpecial Judge\'s Court\b', r'\bSpeedy Trial Tribunal\b', r'\bMobile Court\b',
        r'\bcourt compound\b', r'\bjudicial service\b', r'\bBangladesh Judicial Service Commission\b',
        r'\badvocate\b', r'\blawyer\b', r'\bbarrister\b', r'\battorney\b', r'\bsolicitor\b',
        r'\bpleader\b', r'\bmuktar\b', r'\bpublic prosecutor\b', r'\bPP\b', r'\badditional public prosecutor\b',
        r'\bAPP\b', r'\bgovernment counsel\b', r'\bdefense counsel\b', r'\bdefense lawyer\b',
        r'\bstate counsel\b', r'\bstate defender\b', r'\blegal aid lawyer\b', r'\bpanel lawyer\b',
        r'\bretainer\b', r'\bsenior advocate\b', r'\bjunior advocate\b', r'\bchamber\b',
        r'\bchamber practice\b', r'\bBar Council\b', r'\bBangladesh Bar Council\b',
        r'\bBar Council enrollment\b', r'\bBar Council exam\b', r'\bBar Council license\b',
        r'\bBar Association\b', r'\bDistrict Bar Association\b', r'\bSupreme Court Bar Association\b',
        r'\blegal practitioner\b', r'\bfirst information report\b', r'\bFIR\b', r'\bGD\b',
        r'\bgeneral diary\b', r'\bcognizance\b', r'\bcharge sheet\b', r'\bchargesheet\b',
        r'\bfinal report\b', r'\bpetition\b', r'\bplaint\b', r'\bwritten statement\b',
        r'\baffidavit\b', r'\baffidavit of service\b', r'\bwitness affidavit\b',
        r'\bpower of attorney\b', r'\bPOA\b', r'\bvakalatnama\b', r'\bvakalat\b', r'\bvakil\b',
        r'\bcross-examination\b', r'\bexamination-in-chief\b', r'\bre-examination\b',
        r'\bexamination of witness\b', r'\bdeposition\b', r'\bevidence\b', r'\bexhibit\b',
        r'\bmaterial exhibit\b', r'\bdocumentary evidence\b', r'\boral evidence\b',
        r'\bcircumstantial evidence\b', r'\bhearsay evidence\b', r'\bexpert evidence\b',
        r'\bfinding\b', r'\bjudgment\b', r'\bjudgement\b', r'\bdecree\b', r'\border\b',
        r'\binterim order\b', r'\bad-interim order\b', r'\bstay order\b', r'\binjunction\b',
        r'\btemporary injunction\b', r'\bpermanent injunction\b', r'\bmandatory injunction\b',
        r'\brestraining order\b', r'\bwarrant\b', r'\barrest warrant\b', r'\bsearch warrant\b',
        r'\bproduction warrant\b', r'\bremand\b', r'\bpolice remand\b', r'\bjudicial remand\b',
        r'\bbail\b', r'\binterim bail\b', r'\bregular bail\b', r'\banticipatory bail\b',
        r'\bcancellation of bail\b', r'\bbail bond\b', r'\bsurety\b', r'\bprison\b', r'\bjail\b',
        r'\bcorrectional center\b', r'\bprisoner\b', r'\bunder-trial prisoner\b', r'\bUTP\b',
        r'\bconvict\b', r'\bcondemned prisoner\b', r'\bcognizable offence\b', r'\bnon-cognizable offence\b',
        r'\bbailable offence\b', r'\bnon-bailable offence\b', r'\bcompoundable offence\b',
        r'\bnon-compoundable offence\b', r'\binvestigation\b', r'\binvestigating officer\b', r'\bIO\b',
        r'\bpolice investigation\b', r'\bCID\b', r'\bCriminal Investigation Department\b', r'\bDB\b',
        r'\bDetective Branch\b', r'\bRAB\b', r'\bRapid Action Battalion\b', r'\bpolice\b', r'\bOC\b',
        r'\bOfficer-in-Charge\b', r'\bSI\b', r'\bSub-Inspector\b', r'\bASI\b',
        r'\bAssistant Sub-Inspector\b', r'\bInspector\b', r'\bASP\b', r'\bAssistant Superintendent of Police\b',
        r'\bSP\b', r'\bSuperintendent of Police\b', r'\bDIG\b', r'\bDeputy Inspector General\b',
        r'\bIGP\b', r'\bInspector General of Police\b', r'\bPBI\b', r'\bPolice Bureau of Investigation\b',
        r'\bprosecution\b', r'\bdefense\b', r'\bdefence\b', r'\btrial\b', r'\bsessions trial\b',
        r'\bmagisterial trial\b', r'\bsummary trial\b', r'\bspeedy trial\b', r'\bplea bargaining\b',
        r'\bplea\b', r'\bguilty plea\b', r'\bnot guilty plea\b', r'\bconviction\b', r'\bacquittal\b',
        r'\bdischarge\b', r'\bsentence\b', r'\bdeath sentence\b', r'\blife imprisonment\b',
        r'\bimprisonment for life\b', r'\brigorous imprisonment\b', r'\bRI\b', r'\bsimple imprisonment\b',
        r'\bfine\b', r'\bcompensation\b', r'\bprobation\b', r'\bparole\b', r'\bcivil suit\b',
        r'\bcivil appeal\b', r'\bcivil revision\b', r'\bcivil motion\b', r'\btitle suit\b',
        r'\brecovery of possession\b', r'\bdeclaration of title\b', r'\bpartition suit\b',
        r'\brent suit\b', r'\bmoney suit\b', r'\bexecution\b', r'\bexecution case\b',
        r'\bexecution of decree\b', r'\battachment\b', r'\battachment before judgment\b',
        r'\bsale certificate\b', r'\bdelivery of possession\b', r'\brestitution\b', r'\bmesne profit\b',
        r'\bdamages\b', r'\bland law\b', r'\bland dispute\b', r'\bland survey\b', r'\bRS record\b',
        r'\bSA record\b', r'\bCS record\b', r'\bkhatian\b', r'\bdag\b', r'\bporcha\b', r'\bdalil\b',
        r'\bkabala\b', r'\bheba\b', r'\bwasiyatnama\b', r'\bdeed\b', r'\bland registration\b',
        r'\bsub-registry office\b', r'\bAC Land\b', r'\bDC Office\b', r'\bUNO Office\b',
        r'\bland office\b', r'\btahsildar\b', r'\bsurveyor\b', r'\bland boundary\b',
        r'\bland measurement\b', r'\badministrative order\b', r'\badministrative appeal\b',
        r'\badministrative tribunal\b', r'\bAT\b', r'\bAdministrative Tribunal\b',
        r'\badministrative review\b', r'\bdepartmental proceeding\b', r'\bshow-cause notice\b',
        r'\bcharge sheet\b', r'\bdepartmental punishment\b', r'\bcompulsory retirement\b',
        r'\bremoval\b', r'\bdismissal\b', r'\bgovernment order\b', r'\bGO\b', r'\bcirculation\b',
        r'\bcircular\b', r'\bmemorandum\b', r'\bmemo\b', r'\bnotification\b', r'\bpublic notice\b',
        r'\bhuman rights\b', r'\bhuman rights violation\b', r'\bNational Human Rights Commission\b',
        r'\bNHRC\b', r'\blegal aid\b', r'\bNational Legal Aid Services Organization\b', r'\bNLASO\b',
        r'\bdistrict legal aid committee\b', r'\bupazila legal aid committee\b', r'\bfree legal aid\b',
        r'\blegal aid clinic\b', r'\bpro bono\b', r'\bpublic interest litigation\b', r'\bPIL\b',
        r'\bamicus curiae\b', r'\bright to information\b', r'\bRTI\b', r'\bInformation Commission\b',
        r'\binformation officer\b', r'\bappellate authority\b', r'\bACC\b', r'\bAnti-Corruption Commission\b',
        r'\bcorruption\b', r'\bgraft\b', r'\bbribery\b', r'\bembezzlement\b', r'\bmisappropriation\b',
        r'\bassets declaration\b', r'\bwealth statement\b', r'\binquiry\b', r'\binvestigation\b',
        r'\bcharge sheet\b', r'\bspecial judge court\b', r'\binternational tribunal\b', r'\bICT\b',
        r'\bInternational Crimes Tribunal\b', r'\bInternational Crimes Tribunal Bangladesh\b',
        r'\bwar crimes\b', r'\bcrimes against humanity\b', r'\bgenocide\b', r'\b1971 Liberation War\b',
        r'\bwar criminal\b', r'\bwar crimes trial\b', r'\bInternational Criminal Court\b', r'\bICC\b',
        r'\bInternational Court of Justice\b', r'\bICJ\b', r'\bUN convention\b', r'\btreaty\b',
        r'\bprotocol\b', r'\bruling party\b', r'\bopposition party\b', r'\bcoalition government\b',
        r'\balliance\b', r'\bparliamentary party\b', r'\bparty chief\b', r'\bparty president\b',
        r'\bgeneral secretary\b', r'\bpresidium\b', r'\bpresidium member\b', r'\bcentral committee\b',
        r'\bexecutive committee\b', r'\bworking committee\b', r'\bstanding committee\b',
        r'\bdistrict committee\b', r'\bupazila committee\b', r'\bunion committee\b',
        r'\bpolitical alliance\b', r'\b20-party alliance\b', r'\b14-party alliance\b',
        r'\bJatiya Oikyafront\b', r'\bJatiya Party\b', r'\bBNP\b', r'\bBangladesh Nationalist Party\b',
        r'\bAwami League\b', r'\bAL\b', r'\bJamaat-e-Islami\b', r'\bhefazat\b', r'\bHefazat-e-Islam\b',
        r'\bhartal\b', r'\bpolitical rally\b', r'\bprocession\b', r'\bsit-in\b', r'\bhuman chain\b',
        r'\bblockade\b', r'\bsiege\b', r'\broad march\b', r'\bpublic meeting\b', r'\bgrand rally\b',
        r'\bstate of emergency\b', r'\bemergency powers\b', r'\bcurfew\b', r'\bsection 144\b',
        r'\bsection 144 imposed\b', r'\bprohibitory order\b', r'\bban on assembly\b',
        r'\bsecurity alert\b', r'\bhigh alert\b', r'\bred alert\b', r'\bsecurity forces\b',
        r'\barmed forces\b', r'\bmilitary\b', r'\barmy\b', r'\bparamilitary\b', r'\bBGB\b',
        r'\bBorder Guard Bangladesh\b', r'\bAnsar\b', r'\bVDP\b', r'\bVillage Defence Party\b',
        r'\bCoast Guard\b', r'\bpro bono publico\b', r'\bex parte\b', r'\bin camera\b',
        r'\bprima facie\b', r'\binter alia\b', r'\bsuo moto\b', r'\bsuo motu\b', r'\bbona fide\b',
        r'\bmala fide\b', r'\bde facto\b', r'\bde jure\b', r'\bultra vires\b', r'\bintra vires\b',
        r'\bquantum of punishment\b', r'\bmitigating circumstances\b', r'\baggravating circumstances\b',
        r'\bplea of alibi\b', r'\bplea of insanity\b', r'\bplea of self-defense\b',
        r'\bplea of limitation\b', r'\bplea of res judicata\b', r'\bplea of autrefois acquit\b',
        r'\bplea of autrefois convict\b', r'\bpolice line\b', r'\bthana\b', r'\bpolice box\b',
        r'\bpolice control room\b', r'\barmed police\b', r'\bAPBn\b', r'\bArmed Police Battalion\b',
        r'\bpolice training center\b', r'\bpolice hospital\b', r'\bpolice lines\b', r'\bpolice barracks\b',
        r'\bSB\b', r'\bSpecial Branch\b', r'\bDB\b', r'\bDetective Branch\b', r'\bCTTC\b',
        r'\bCounter Terrorism and Transnational Crime\b', r'\bTSB\b', r'\bTelephone Surveillance Bureau\b',
        r'\bNSI\b', r'\bNational Security Intelligence\b', r'\bDGFI\b', r'\bDirectorate General of Forces Intelligence\b',
        r'\blaw college\b', r'\blaw department\b', r'\bfaculty of law\b', r'\bDhaka University Law Faculty\b',
        r'\blaw campus\b', r'\bLLB\b', r'\bLLB (Hons)\b', r'\bLLM\b', r'\bPhD in Law\b',
        r'\bBar Vocational Course\b', r'\bBar examination\b', r'\bJudicial Service Commission\b',
        r'\bJudicial Service examination\b', r'\bBCS Judicial\b', r'\blaw journal\b',
        r'\bBangladesh Law Reports\b', r'\bBLR\b', r'\bDhaka Law Reports\b', r'\bDLR\b',
        r'\bBangladesh Penal Code\b', r'\bCode of Criminal Procedure\b', r'\bCrPC\b',
        r'\bCode of Civil Procedure\b', r'\bCPC\b', r'\bTransfer of Property Act\b',
        r'\bLimitation Act\b', r'\bMuslim Personal Law\b', r'\bHindu Personal Law\b',
        r'\bChristian Personal Law\b', r'\bMuslim Marriage and Divorce Act\b',
        r'\bFamily Courts Ordinance\b', r'\bDowry Prohibition Act\b', r'\bAcid Crime Control Act\b',
        r'\bAcid Control Act\b', r'\bWomen and Children Repression Prevention Act\b',
        r'\bCyber Security Act\b', r'\bDigital Security Act\b', r'\bInformation and Communication Technology Act\b'
    ],
    'common_phrases': [
        r'\bwhat is your good name\b', r'\bgood name\b', r'\bwhere are you from\b',
        r'\byour home district\b', r'\bwhat is your home district\b', r'\bwhich district\b',
        r'\bare you from Dhaka\b', r'\bbhalo acho\b', r'\bhow are you\b', r'\bAlhamdulillah\b',
        r'\bAllah Hafeez\b', r'\bKhoda Hafeez\b', r'\bin sha Allah\b', r'\bthank you\b',
        r'\bthanks\b', r'\bdhonnobad\b', r'\bwelcome\b', r'\bwelcome to my house\b',
        r'\bplease come\b', r'\bplease sit\b', r'\bbosho\b', r'\bhave some tea\b',
        r'\bcha khaben\b', r'\bapni\b', r'\btumi\b', r'\btui\b', r'\bsir\b', r'\bmadam\b',
        r'\bbhai\b', r'\bapa\b', r'\bchacha\b', r'\bkhala\b', r'\buncle\b', r'\baunty\b',
        r'\bSir, please\b', r'\bMadam, please\b', r'\bplease do the needful\b',
        r'\bplease do the necessary\b', r'\barrange the same\b',
        r'\bplease revert\b', r'\bkindly revert back\b', r'\bplease advise\b', r'\bplease suggest\b',
        r'\bwould be obliged\b', r'\bwould be grateful\b', r'\byour early response is highly appreciated\b',
        r'\byour kind cooperation is sought\b', r'\btoday morning\b', r'\btoday night\b',
        r'\byesterday night\b', r'\bday before yesterday\b', r'\bday after tomorrow\b',
        r'\bmorning time\b', r'\bevening time\b', r'\bnight time\b', r'\bhalf past eight\b',
        r'\bquarter to\b', r'\bquarter past\b', r'\b10 minutes past\b', r'\btwenty minutes to\b',
        r'\bwhat is the time now\b', r'\btime ta koto\b', r'\bclock time\b', r'\bo\'clock\b',
        r'\bI am going\b', r'\bI am coming\b',
        r'\bI will come\b', r'\bcoming from\b', r'\bwhat to do\b', r'\bki ar korbo\b',
        r'\bwhat can I do\b', r'\bwhat to say\b', r'\bwhat to tell you\b', r'\bso long\b',
        r'\bI will meet you\b', r'\bwe will meet\b', r'\bwe will catch up\b', r'\bhave your lunch\b',
        r'\bhave your dinner\b', r'\byou have eaten\b', r'\bkhabar kheyecho\b', r'\bhave you eaten\b',
        r'\bhave you had your meal\b', r'\bI just now ate\b', r'\bI just now finished\b',
        r'\bjust now\b', r'\bhe just now left\b', r'\bout of station\b', r'\bI will be out of station\b',
        r'\bon leave\b', r'\bI am on leave today\b', r'\bcasual leave\b', r'\bCL\b', r'\bmedical leave\b',
        r'\bML\b', r'\bannual leave\b', r'\bAL\b', r'\bleave application\b', r'\bleave letter\b',
        r'\bhalf-day leave\b', r'\bshort leave\b', r'\bjoining letter\b', r'\bappointment letter\b',
        r'\bpromotion letter\b', r'\brelieving letter\b', r'\bexperience certificate\b',
        r'\bsalary certificate\b', r'\bNOC\b', r'\bNo Objection Certificate\b', r'\bencashment\b',
        r'\bleave encashment\b', r'\bPF\b', r'\bProvident Fund\b', r'\bincome tax return\b',
        r'\bTIN certificate\b', r'\bwhat is your educational qualification\b', r'\bwhat is your qualification\b',
        r'\bI passed SSC in 2010\b', r'\bI passed HSC\b', r'\bI am a student of\b', r'\bI studied in\b',
        r'\bmy educational background\b', r'\bboard exam\b', r'\bpublic exam\b', r'\bprivate candidate\b',
        r'\bregular student\b', r'\bcollege life\b', r'\bhall life\b', r'\bmajor subject\b',
        r'\bsubject combination\b', r'\boptional subject\b', r'\b4th subject\b', r'\bI got GPA 5\b',
        r'\bI got A+\b', r'\bI got golden A+\b', r'\bI got scholarship\b', r'\btalent pool scholarship\b',
        r'\bgeneral scholarship\b', r'\badmission test\b', r'\bvarsity admission\b', r'\buniversity life\b',
        r'\bprivate university\b', r'\bpublic university\b', r'\bmedical college\b', r'\bengineering college\b',
        r'\bcousin brother\b', r'\bcousin sister\b', r'\bbrother-in-law\b', r'\bsister-in-law\b',
        r'\buncle\b', r'\baunty\b', r'\bmy namesake\b', r'\bmy shomnam\b', r'\bmy father\'s name is\b',
        r'\bmy mother\'s name is\b', r'\bonly child\b', r'\belder brother\b', r'\bolder brother\b',
        r'\byounger brother\b', r'\blittle brother\b', r'\belder sister\b', r'\bolder sister\b',
        r'\byounger sister\b', r'\blittle sister\b', r'\bmy parents\b', r'\bmy grandparents\b',
        r'\bstay with family\b', r'\bnuclear family\b', r'\bextended family\b', r'\bjoint family\b',
        r'\bfamily members\b', r'\brelatives\b', r'\batmiya swajan\b', r'\barranged marriage\b',
        r'\blove marriage\b', r'\bmarriage proposal\b', r'\bproposal\b', r'\bsee the girl\b',
        r'\bsee the boy\b', r'\bdekha dekhi\b', r'\bpoti\b', r'\bengagement\b',
        r'\bengagement ceremony\b', r'\bgaye holud\b', r'\bholud\b', r'\bwedding ceremony\b',
        r'\bbiyer shadi\b', r'\bbou bhat\b', r'\bwalima\b', r'\bkabin nama\b', r'\bdower\b',
        r'\bdenmohor\b', r'\bbride\b', r'\bkone\b', r'\bgroom\b', r'\bbor\b', r'\bnewly married\b',
        r'\bnewlywed\b', r'\bhoneymoon\b', r'\bEid Mubarak\b', r'\bEid greeting\b', r'\bEidgah\b',
        r'\bEid prayer\b', r'\bEid reunion\b', r'\bEid festival\b', r'\bEid-ul-Fitr\b',
        r'\bEid-ul-Adha\b', r'\bKorbani Eid\b', r'\bQurbani\b', r'\bEid shopping\b', r'\bEid gift\b',
        r'\bEidi\b', r'\bnew dress\b', r'\bPohela Boishakh\b', r'\bBengali New Year\b',
        r'\bMangal Shobhajatra\b', r'\bDurga Puja\b', r'\bPuja\b', r'\bPuja pandal\b',
        r'\bSaraswati Puja\b', r'\bLakshmi Puja\b', r'\bKali Puja\b', r'\bDiwali\b',
        r'\bChristmas\b', r'\bBuddha Purnima\b', r'\bShab-e-Barat\b', r'\bShab-e-Qadr\b',
        r'\bJumatul Bidah\b', r'\bChand Raat\b', r'\bhave you eaten\b', r'\bkhabar kheyecho\b',
        r'\bwhat did you eat\b', r'\bki kheyecho\b', r'\bI ate rice\b', r'\bvat kheyechi\b',
        r'\bI had fish\b', r'\bmach kheyechi\b', r'\bI had meat\b', r'\bgosto kheyechi\b',
        r'\bbiryani\b', r'\bkachchi biryani\b', r'\bpolao\b', r'\bpulao\b', r'\brice and curry\b',
        r'\bfish curry\b', r'\bmacher jhol\b', r'\bdaal\b', r'\bdaal bhaat\b', r'\bbhorta\b',
        r'\bmachher bhorta\b', r'\bbhaji\b', r'\balu bhaji\b', r'\bparatha\b', r'\bluchi\b',
        r'\bchira\b', r'\bmuri\b', r'\bchanachur\b', r'\bcha\b', r'\bcha khaben\b',
        r'\bseven-layer tea\b', r'\bchotpoti\b', r'\bfuchka\b', r'\bphuchka\b', r'\bsingara\b',
        r'\bsamosa\b', r'\bjhalmuri\b', r'\bhaleem\b', r'\bhow much\b', r'\bkoto taka\b',
        r'\bwhat is price\b', r'\bprice is high\b', r'\bexpensive\b', r'\btoo costly\b',
        r'\bcan you give discount\b', r'\bdiscount please\b', r'\bbargaining\b', r'\bdam\b',
        r'\bthis is too much\b', r'\bI will give you\b', r'\bmy final price\b',
        r'\bwhat is your final price\b', r'\bplease weigh\b', r'\bokhon\b', r'\bhalf kilo\b',
        r'\badha kilo\b', r'\bone kilo\b', r'\bek kilo\b', r'\btwo hundred grams\b',
        r'\bpiece rate\b', r'\bkoyla dam\b', r'\bwholesale price\b', r'\bpikar dam\b',
        r'\bretail price\b', r'\bkhucra dam\b', r'\btake away\b', r'\bpack it\b', r'\bout of station\b',
        r'\bgoing home\b', r'\bdeshe jabo\b', r'\bvillage home\b', r'\bgramer bari\b',
        r'\bgoing to village\b', r'\bhome district\b', r'\bdistrict town\b', r'\bticket booking\b',
        r'\badvance ticket\b', r'\bcounter ticket\b', r'\bonline ticket\b', r'\bSMS ticket\b',
        r'\bbus stand\b', r'\blaunch ghat\b', r'\brailway station\b', r'\bairport\b', r'\bboarding\b',
        r'\bhow long journey\b', r'\bhow many hours\b', r'\btravel time\b', r'\bbooked ticket\b',
        r'\bwaiting list\b', r'\bWL\b', r'\bRAC\b', r'\bconfirmed ticket\b', r'\bI am not feeling well\b',
        r'\bI have fever\b', r'\bjor\b', r'\bcold and cough\b', r'\bheadache\b', r'\bmathay bytha\b',
        r'\bstomach ache\b', r'\bpethe bytha\b', r'\bdiarrhea\b', r'\bamasha\b', r'\btyphoid\b',
        r'\bdoctor\'s chamber\b', r'\bmedicine shop\b', r'\bpharmacy\b', r'\bchemist\b',
        r'\bpathology\b', r'\bdiagnostic center\b', r'\btest report\b', r'\bcBCA test\b',
        r'\bx-ray\b', r'\becg\b', r'\bultrasound\b', r'\bblood pressure\b', r'\bBP\b',
        r'\bsugar test\b', r'\bmedicine\b', r'\boshudh\b', r'\btake medicine\b',
        r'\bhave you taken medicine\b', r'\bon time medicine\b', r'\badvised by doctor\b',
        r'\bfollow up\b', r'\bcheck up\b', r'\bweather is hot\b', r'\bgorom\b', r'\bhot season\b',
        r'\bgorom kal\b', r'\bmonsoon\b', r'\bborsha kal\b', r'\brainy season\b', r'\bheavy rain\b',
        r'\bbristi\b', r'\bcloudy sky\b', r'\bstorm\b', r'\bjhor\b', r'\bcyclone\b',
        r'\bthunderstorm\b', r'\bthunder\b', r'\bbaj\b', r'\blightning\b', r'\bweather is nice\b',
        r'\bweather is pleasant\b', r'\bcold weather\b', r'\bthanda\b', r'\bwinter season\b',
        r'\bshit kal\b', r'\bair pollution\b', r'\bheat wave\b', r'\bcold wave\b', r'\bdrought\b',
        r'\bkhara\b', r'\bflood\b', r'\bbonna\b', r'\bwaterlogging\b', r'\bpani joma\b',
        r'\bup to mark\b', r'\bnot up to the mark\b', r'\bby hook or by crook\b',
        r'\bby leaps and bounds\b', r'\bfrom time to time\b', r'\btime to time\b',
        r'\bnow a days\b', r'\bthese days\b', r'\bin current times\b', r'\bin present time\b',
        r'\bthis present time\b', r'\bas per\b', r'\bas per rules\b', r'\bas per my knowledge\b',
        r'\bas per my opinion\b', r'\bin my opinion\b', r'\bmy point of view\b', r'\bwith due respect\b',
        r'\bwith all due respect\b', r'\bmore or less\b', r'\bwhat to do\b', r'\bki ar korbo\b',
        r'\bwhat can be done\b', r'\bit is what it is\b', r'\bthat is matter\b',
        r'\bthat is point\b', r'\b matter is\b', r'\bfact is\b', r'\bactually\b',
        r'\bactually speaking\b', r'\bto be honest\b', r'\bhonestly speaking\b', r'\bfrankly speaking\b',
        r'\bgenerally speaking\b', r'\btelling you truth\b', r'\btruth be told\b',
        r'\bI am telling you\b', r'\byou know\b', r'\byou see\b', r'\bokay\b', r'\bthik ache\b',
        r'\bfine\b', r'\bvalo\b', r'\bnot bad\b', r'\bso so\b', r'\bI see\b', r'\bI understand\b',
        r'\byes, I know\b', r'\bno, I don\'t know\b', r'\bmaybe\b', r'\bhoyto\b', r'\bpossibly\b',
        r'\bnot possible\b', r'\bimpossible\b', r'\bno problem\b', r'\bno issue\b', r'\bno tension\b',
        r'\bno worries\b', r'\bdon\'t worry\b', r'\bchinta korben na\b', r'\byou\'re welcome\b',
        r'\bwelcome\b', r'\bthank you\b', r'\bthanks\b', r'\bit\'s okay\b', r'\bnever mind\b',
        r'\bdosen\'t matter\b', r'\bwhat a beautiful\b', r'\bwhat a nice\b', r'\bwhat a shame\b',
        r'\bwhat a pity\b', r'\bwhat a waste\b', r'\bso nice\b', r'\bvery good\b', r'\bkhub valo\b',
        r'\bvery bad\b', r'\bkhub kharap\b', r'\boh my god\b', r'\bOMG\b', r'\boh Allah\b',
        r'\bwow\b', r'\bunbelievable\b', r'\bincredible\b', r'\bmind blowing\b',
        r'\bout of this world\b', r'\bawesome\b', r'\bfantastic\b', r'\btremendous\b',
        r'\bhartal\b', r'\bandolan\b', r'\bprocession\b', r'\bblockade\b', r'\bsiege\b',
        r'\broad march\b', r'\bhuman chain\b', r'\bsit-in\b', r'\bpublic meeting\b', r'\bgrand rally\b',
        r'\bpolitical rally\b', r'\belection manifesto\b', r'\bvote rigging\b', r'\belection irregularities\b',
        r'\bcaretaker government\b', r'\binterim government\b', r'\bfreedom fighter\b',
        r'\bLiberation War\b', r'\b1971\b', r'\bbangabandhu\b', r'\bdigital Bangladesh\b',
        r'\bvision 2021\b', r'\bvision 2041\b', r'\bsmart Bangladesh\b', r'\beve teasing\b',
        r'\bfatwa\b', r'\bacidity\b', r'\bacid violence\b', r'\bdowny\b', r'\bdowny death\b',
        r'\bchild marriage\b', r'\brepression\b', r'\bviolence against women\b', r'\bhuman trafficking\b',
        r'\bchild labor\b', r'\briver erosion\b', r'\bclimate refugee\b', r'\brohingya\b',
        r'\bforcibly displaced\b', r'\bmobile recharge\b', r'\bbKash\b', r'\bNagad\b',
        r'\bmobile banking\b', r'\bsend money\b', r'\bcash out\b', r'\bmobile number\b',
        r'\bSIM card\b', r'\binternet package\b', r'\bdata pack\b', r'\bFacebook ID\b',
        r'\bFacebook page\b', r'\bgroup\b', r'\bstatus\b', r'\bpost\b', r'\bshare\b', r'\blike\b',
        r'\blikes\b', r'\bcomment\b', r'\bmessenger\b', r'\bWhatsApp\b', r'\bIMO\b', r'\bviber\b',
        r'\bzoom\b', r'\bgoogle meet\b', r'\bonline class\b', r'\bzoom class\b',
        r'\bin this regard\b', r'\bin this connection\b', r'\bin this context\b',
        r'\bwith reference to\b', r'\bwith regard to\b', r'\bwith respect to\b', r'\bpertaining to\b',
        r'\bregarding this matter\b', r'\bas regards\b', r'\bconcerning the above\b',
        r'\breferring to your\b', r'\bin reply to\b', r'\bin response to\b', r'\bI would like to\b',
        r'\bI wish to\b', r'\bI want to\b', r'\bI intend to\b', r'\bI propose to\b',
        r'\bI suggest that\b', r'\bI recommend that\b', r'\bmy humble request\b',
        r'\bmy sincere request\b', r'\bmy earnest request\b', r'\bI would be grateful if\b',
        r'\bI would be obliged if\b', r'\byour kind attention\b', r'\bfor your kind attention\b',
        r'\bfor your kind consideration\b', r'\bfor your perusal\b', r'\bfor your information\b',
        r'\bfor your reference\b', r'\bplease find attached\b', r'\battached herewith\b',
        r'\bherewith attached\b', r'\bplease see attached\b', r'\bplease refer to the attached\b',
        r'\bmore than\b', r'\bless than\b', r'\babout\b', r'\baround\b', r'\bapproximately\b',
        r'\bproximate\b', r'\bmaximum\b', r'\bminimum\b', r'\bat least\b', r'\bat most\b',
        r'\bat the most\b', r'\ba lot\b', r'\bmany\b', r'\bso many\b', r'\btoo much\b',
        r'\bquite a lot\b', r'\bfew\b', r'\ba few\b', r'\blittle\b', r'\ba little\b',
        r'\bquite a few\b', r'\bmost of the\b', r'\bmost of the time\b', r'\bmost of the people\b',
        r'\bin most cases\b', r'\bin some cases\b', r'\bin many cases\b', r'\bvery\b', r'\bso\b',
        r'\btoo\b', r'\bvery much\b', r'\bso much\b', r'\breally\b', r'\bquite\b',
        r'\bpractically\b', r'\bbasically\b', r'\bactually\b', r'\bliterally\b', r'\bseriously\b',
        r'\breally seriously\b', r'\bdeadly\b', r'\bfully\b', r'\btotally\b', r'\bcompletely\b',
        r'\babsolutely\b', r'\bas...as\b', r'\bthe same as\b', r'\bdifferent from\b',
        r'\bdifferent than\b', r'\bdifferent to\b', r'\bsimilar to\b', r'\blike\b', r'\blike as\b',
        r'\bsuch as\b', r'\bfor example\b', r'\bfor instance\b', r'\bet cetera\b', r'\betc\b',
        r'\bcan be able to\b', r'\bwill be able to\b', r'\bhave to\b', r'\bhas to\b', r'\bhad to\b',
        r'\bmust have to\b', r'\bneed to\b', r'\bneeds to\b', r'\bneeded to\b',
        r'\bshould have to\b', r'\bwould have to\b', r'\bmight have to\b', r'\bI just now ate\b',
        r'\bI just now finished\b', r'\bI just now came\b', r'\bI just now did\b',
        r'\bDid you eat yet\b', r'\bDid you finish yet\b', r'\bDid you go yet\b',
        r'\bDid you come yet\b', r'\bI never did that\b', r'\bI never saw that\b',
        r'\bI never went there\b', r'\bHe just left\b', r'\bShe just came\b', r'\bThey just arrived\b',
        r'\bin search of\b', r'\bin need of\b', r'\bin want of\b', r'\bin favour of\b',
        r'\bin support of\b', r'\bin spite of\b', r'\binstead of\b', r'\bin place of\b',
        r'\bin terms of\b', r'\bin case of\b', r'\bin view of\b', r'\bin light of\b',
        r'\bin the light of\b', r'\bon behalf of\b', r'\bon account of\b', r'\bon the basis of\b',
        r'\bon the grounds of\b', r'\bwith a view to\b', r'\bwith an eye to\b', r'\ba lot of\b',
        r'\blots of\b', r'\bplenty of\b', r'\ba number of\b', r'\ba great number of\b',
        r'\ba large number of\b', r'\ba huge number of\b', r'\ba small number of\b',
        r'\ba limited number of\b', r'\ba majority of\b', r'\ba minority of\b', r'\ba handful of\b',
        r'\ba couple of\b', r'\ba dozen of\b', r'\bhundreds of\b', r'\bthousands of\b',
        r'\blakhs of\b', r'\bcrores of\b', r'\bcountless\b', r'\binnumerable\b',
        r'\bonce upon a time\b', r'\ba long time ago\b', r'\bmany years ago\b', r'\bin the past\b',
        r'\bin the old days\b', r'\bin those days\b', r'\bin recent times\b', r'\bin modern times\b',
        r'\bin contemporary times\b', r'\bin the present time\b', r'\bin the future\b',
        r'\bin the near future\b', r'\bin the distant future\b', r'\bin the days to come\b',
        r'\bin the times ahead\b', r'\bfor the time being\b', r'\bfor the moment\b', r'\bfor now\b',
        r'\bfor the present\b', r'\bas of now\b', r'\bas of today\b', r'\bas of yet\b',
        r'\bup until now\b', r'\bup to now\b', r'\buntil now\b', r'\bso far\b', r'\bif possible\b',
        r'\bif needed\b', r'\bif required\b', r'\bif necessary\b', r'\bif applicable\b', r'\bif any\b',
        r'\bif at all\b', r'\bif not\b', r'\bif so\b', r'\bin case\b', r'\bin the event of\b',
        r'\bin the event that\b', r'\bprovided that\b', r'\bproviding that\b', r'\bsubject to\b',
        r'\bdepending on\b', r'\beven if\b', r'\beven though\b', r'\balthough\b', r'\bthough\b',
        r'\bdespite\b', r'\bdespite the fact that\b', r'\bin spite of\b', r'\bin spite of the fact that\b',
        r'\bregardless of\b', r'\bno matter what\b', r'\bno matter how\b', r'\bno matter where\b',
        r'\bno matter when\b', r'\bbecause of\b', r'\bon account of\b', r'\bdue to\b', r'\bowing to\b',
        r'\bas a result of\b', r'\bas a consequence of\b', r'\bin consequence of\b', r'\bthanks to\b',
        r'\bresulting in\b', r'\bleading to\b', r'\bcontributing to\b', r'\bgiving rise to\b',
        r'\bgiving way to\b', r'\bdiscuss about\b', r'\bin station\b', r'\bdid the needful\b', r'\brunners-up\b',
        r'\bmothers-in-law\b',r'\bfollowed to the letter\b', r'\brub it in (?:their|my|your)? faces?\b',
        r'\boff the hook\b', r'\bapple of (?:my|your|his|her|their) eye\b', r'\bkilling (?:them|him|her) with kindness\b',
        r'\bin (?:my|his|her|their) element\b', r'\bworld at (?:my|his|her|their) feet\b', r'\brelationship goals\b',
        r'\bfixed price is a myth\b', r'\bzeal and zest\b',
        r'\bstart the bidding\b', r'\bpassers-by\b'
    ],
'passive_modals': [
    r'\bwould be\s+[Ved]\b',        # "would be telecast", "would be relayed"
    r'\bshould be\s+[Ved]\b',       # "should be treated"
    ],
'just_now_variants': [
    r'\bhave just now\s+Ved\b',     # "I have just now finished"
    r'\bhas just now\s+Ved\b',
    ],

'collective_nouns': [
        r'\bteam is having\b', r'\bgovernment is wanting\b', r'\bcompany is needing\b',
        r'\bfamily is understanding\b', r'\bstaff is knowing\b', r'\bcommittee is believing\b',
        r'\bclass is preferring\b', r'\b board is thinking\b', r'\bgroup is liking\b',
        r'\baudience is loving\b', r'\bband is owning\b', r'\bcrew is possessing\b',
        r'\bcouple is wanting\b', r'\bpopulation is needing\b', r'\bpublic is knowing\b',
        r'\bpress is believing\b', r'\bteam was having\b', r'\bfamily was wanting\b',
        r'\bcommittee was needing\b', r'\bcompany was understanding\b', r'\bgroup was knowing\b'
    ],
    'verb_tenses': [
        r'\bI just now ate\b', r'\bI just now finished\b', r'\bI just now saw\b',
        r'\bI just now came\b', r'\bI just now went\b', r'\bI just now did\b',
        r'\bI just now left\b', r'\bI just now arrived\b', r'\bI just now called\b',
        r'\bHe just now left\b', r'\bShe just now came\b', r'\bThey just now arrived\b',
        r'\bI have just now eaten\b', r'\bI have just now finished\b', r'\bI have just now seen\b',
        r'\bI have just now come\b', r'\bI am here since morning\b',
        r'\bI am waiting for two hours\b', r'\bI know him for five years\b',
        r'\bI live here since 2010\b', r'\bI am knowing him for long\b',
        r'\bI am having this car since 2015\b', r'\bI am wanting this for years\b',
        r'\bI did it before he came\b', r'\bI finished when he arrived\b',
        r'\bI ate already when he called\b', r'\bI left before he reached\b',
        r'\bI will finish by tomorrow\b', r'\bI will complete before you come\b',
        r'\bIf I would have known\b', r'\bIf I would have seen\b', r'\bIf I would have gone\b',
        r'\bIf I would have tried\b', r'\bI would have not gone\b', r'\bHe would have not come\b',
        r'\bI didn\'t go until he came\b', r'\bI will not leave until you come\b',
        r'\bIt is two years since I met him\b', r'\bNo sooner did I arrive than he left\b',
        r'\bHardly had I reached when he called\b', r'\bAs soon as I reached, he left\b',
        r'\bWhile I was going, I met him\b', r'\bWhen I was coming, I saw her\b',
        r'\bBy the time I reached, he left\b', r'\bAfter I finished, I went home\b',
        r'\bBefore I left, I called him\b', r'\bSince I met you, my life changed\b',
        r'\bI had already finished when he came\b', r'\bI had never seen such a thing\b',
        r'\bI am going tomorrow\b', r'\bHe is coming next week\b', r'\bThey are arriving tonight\b',
        r'\bHe will come every day\b', r'\bShe will call me often\b', r'\bI used to play football\b',
        r'\bI might can come\b', r'\bHe might can help\b', r'\bYou need not go\b', r'\bHe need not worry\b',
        r'\bI dare not go\b', r'\bHe dare not speak\b', r'\bYou had better go\b', r'\bHe had better leave\b',
        r'\bI would rather stay\b', r'\bHe would rather go\b', r'\bHe talks as if he knew everything\b',
        r'\bIt is time we left\b', r'\bI wish I knew\b', r'\bIf only I knew\b', r'\bwork was done by me\b',
        r'\bI got the work done\b', r'\bHe had his car repaired\b', r'\bShe got her hair cut\b',
        r'\bHe kept on talking\b', r'\bHe went on talking\b', r'\bHe stopped smoking\b',
        r'\bHe stopped to smoke\b', r'\bI remember meeting him\b', r'\bI remembered to meet him\b',
        r'\bI tried calling\b', r'\bI tried to call\b', r'\bThis means changing plans\b',
        r'\bI meant to change plans\b', r'\bI regret saying that\b', r'\bI regret to inform you\b',
        r'\bI am afraid of flying\b', r'\bI am afraid to fly\b', r'\bI am interested in learning\b',
        r'\bI am interested to learn\b', r'\bHe said that he will come\b',
        r'\bShe told me that she is coming\b', r'\bHe asked me what is my name\b',
        r'\bHe told me to go\b', r'\bLet\'s go\b', r'\bLet me go\b', r'\bMake him understand\b',
        r'\bHave it done\b', r'\bGet it done\b', r'\bIt needs cleaning\b', r'\bI want it done\b',
        r'\bI saw him coming\b', r'\bI saw him come\b', r'\bHelp me do it\b', r'\bHelp me to do it\b',
        r'\bPrevent him from going\b', r'\bHe insisted on going\b', r'\bHe apologized for being late\b',
        r'\bThank you for coming\b', r'\bI look forward to meeting you\b', r'\bI used to smoke\b',
        r'\bI am used to smoking\b', r'\bI am about to leave\b', r'\bI am going to go\b',
        r'\bI will go\b', r'\bI shall go\b', r'\bShall I go\?\b', r'\bMay I come in\?\b',
        r'\bI might come\b', r'\bI can do it\b', r'\bCan I go\?\b', r'\bCould you help\?\b',
        r'\bYou should go\b', r'\bYou must go\b', r'\bI have to go\b', r'\bI need to go\b',
        r'\bYou ought to help\b', r'\bI prefer to stay\b', r'\bI prefer staying\b',
        r'\bI like to read\b', r'\bI like reading\b', r'\bI love to travel\b', r'\bI love travelling\b',
        r'\bI hate to wait\b', r'\bI hate waiting\b', r'\bI started to work\b', r'\bI started working\b',
        r'\bI began to understand\b', r'\bI began understanding\b', r'\bI continued to work\b',
        r'\bI continued working\b'
    ],
    'everyday_objects': [
        r'\bflat\b', r'\bbuilding\b', r'\bhouse\b', r'\bquarter\b', r'\bbarracks\b',
        r'\bhostel\b', r'\bmess\b', r'\broom\b', r'\bchala\b', r'\bbaranda\b', r'\bvaranda\b',
        r'\bporch\b', r'\bstairs\b', r'\broof\b', r'\bgarage\b', r'\bstore room\b', r'\balna\b',
        r'\bwardrobe\b', r'\balmari\b', r'\bshowcase\b', r'\bdressing table\b', r'\bstudy table\b',
        r'\bdining table\b', r'\btea table\b', r'\bdivan\b', r'\bkhat\b', r'\btoshak\b',
        r'\bbalish\b', r'\bkatha\b', r'\bcomforter\b', r'\bmosquito net\b', r'\bmoshari\b',
        r'\bfan\b', r'\bstand fan\b', r'\bair cooler\b', r'\bAC\b', r'\bair conditioner\b',
        r'\bgas stove\b', r'\boven\b', r'\bkettle\b', r'\btafa\b', r'\bpatil\b', r'\bhandi\b',
        r'\bdekchi\b', r'\bkarai\b', r'\bbati\b', r'\bglass\b', r'\bmug\b', r'\bplate\b',
        r'\bbowl\b', r'\bthala\b', r'\bwater bottle\b', r'\bflask\b', r'\bthermos\b', r'\bjug\b',
        r'\bchaku\b', r'\bchachi\b', r'\bkhunti\b', r'\bjharjhuri\b', r'\bsil nora\b', r'\bgrinder\b',
        r'\bvat\b', r'\bmach\b', r'\bmeat\b', r'\bgosto\b', r'\bmurgi\b', r'\bmutton\b', r'\bdaal\b',
        r'\bdal\b', r'\btorkari\b', r'\bsobji\b', r'\bbhorta\b', r'\bbhaji\b', r'\bcurry\b',
        r'\brosher jhol\b', r'\bkhichuri\b', r'\bpulao\b', r'\bpilaf\b', r'\bbiryani\b', r'\btehari\b',
        r'\bparatha\b', r'\bluchi\b', r'\bruti\b', r'\bchapati\b', r'\bnan\b', r'\bnaan\b',
        r'\bbiscuit\b', r'\bchips\b', r'\bcrisps\b', r'\bchanachur\b', r'\bmuri\b', r'\bchira\b',
        r'\bkhoi\b', r'\bbadam\b', r'\bchinigura\b', r'\bminiket\b', r'\bpaanta bhat\b', r'\bfuchka\b',
        r'\bphuchka\b', r'\bchatpati\b', r'\bjhalmuri\b', r'\bchotpoti\b', r'\bsingara\b', r'\bsomucha\b',
        r'\bsamosa\b', r'\broll\b', r'\bspring roll\b', r'\bpuri\b', r'\bbeguni\b', r'\bpeyaju\b',
        r'\balur chop\b', r'\bdimer chop\b', r'\btelebhaja\b', r'\bhaleem\b', r'\bhalim\b', r'\bkhichuri\b',
        r'\bchicken roast\b', r'\bkabab\b', r'\bkebab\b', r'\bshikh kabab\b', r'\brezala\b', r'\bkala bhuna\b',
        r'\bcha\b', r'\btea\b', r'\bred tea\b', r'\bmasala cha\b', r'\blebu cha\b', r'\bcold drinks\b',
        r'\blassi\b', r'\bmatha\b', r'\bborhan\b', r'\bsherbet\b', r'\brooh afza\b', r'\bsugarcane juice\b',
        r'\bkhajurer rosh\b', r'\bdaab\b', r'\bwater\b', r'\bpani\b', r'\bmineral water\b', r'\bkola\b',
        r'\bkomola\b', r'\bmalta\b', r'\blebu\b', r'\bpepe\b', r'\banaros\b', r'\bpeyara\b', r'\bjambura\b',
        r'\bdalim\b', r'\bkathal\b', r'\bam\b', r'\blitchi\b', r'\blichu\b', r'\bsoap\b', r'\btal\b',
        r'\bshosa\b', r'\baloo\b', r'\bbegun\b', r'\baubergine\b', r'\bfulkopi\b', r'\bbadhakopi\b',
        r'\blao\b', r'\bchichinga\b', r'\bkorola\b', r'\bdherosh\b', r'\bshim\b', r'\bbarbati\b',
        r'\bmula\b', r'\bgajor\b', r'\bpui shak\b', r'\blaal shak\b', r'\bpalong shak\b', r'\bdhonia\b',
        r'\bcilantro\b', r'\bcoriander\b', r'\bmorich\b', r'\bholud\b', r'\badarak\b', r'\brosun\b',
        r'\bpeyaj\b', r'\bonion\b', r'\bsharee\b', r'\bsari\b', r'\bsaree\b', r'\bsalwar kameez\b',
        r'\bthree piece\b', r'\b3-piece\b', r'\borhni\b', r'\bdupatta\b', r'\borona\b', r'\bpanjabi\b',
        r'\bpunjabi\b', r'\bfatua\b', r'\blungi\b', r'\bgamcha\b', r'\bgenji\b', r'\bunderwear\b',
        r'\bunderpants\b', r'\bpant\b', r'\bpants\b', r'\btrouser\b', r'\btrousers\b', r'\bjeans\b',
        r'\bshirt\b', r'\bT-shirt\b', r'\btee shirt\b', r'\bpolo shirt\b', r'\bjacket\b', r'\bblazer\b',
        r'\bsweater\b', r'\bjumper\b', r'\bhoodie\b', r'\bcardigan\b', r'\bsweatshirt\b', r'\bshoes\b',
        r'\bsandals\b', r'\bslippers\b', r'\bchappal\b', r'\bhawai\b', r'\bbata\b', r'\bapto\b',
        r'\btrainers\b', r'\bsneakers\b', r'\bcasual shoes\b', r'\bformal shoes\b', r'\bcanvas\b',
        r'\bbelt\b', r'\bcap\b', r'\bhat\b', r'\btopi\b', r'\btupi\b', r'\bpayel\b', r'\bchuri\b',
        r'\bshika\b', r'\bpakhi\b', r'\bBanglar Mela\b', r'\bDoorjee\b', r'\bSecrets\b', r'\bWestecs?\b',
        r'\bBexi\b', r'\bNandan\b', r'\bAlmas\b', r'\bDressydale\b', r'\bAnjan\b', r'\bHallmarks\b',
        r'\bEtcetera\b', r'\bSath Rang\b', r'\bGausia Market\b', r'\bUAE Moitry Shopping Complex\b',
        r'\bMascot Plaza\b', r'\bMetro Shopping Mall\b', r'\bRangs Plaza\b', r'\bEastern Plaza\b',
        r'\bIDB Bhaban\b', r'\bOrchid Plaza\b', r'\bPriyangan\b', r'\bCollege Street\b', r'\bDhaka College\b',
        r'\bsoap\b', r'\btiara\b', r'\bwheel\b', r'\blux\b', r'\blifebuoy\b', r'\bmeril\b', r'\bshampoo\b',
        r'\bconditioner\b', r'\bhair oil\b', r'\bnarikol tel\b', r'\bsoybean oil\b', r'\bshorisha tel\b',
        r'\btoothpaste\b', r'\btoothbrush\b', r'\bcolgate\b', r'\btoothpowder\b', r'\bbabool\b', r'\btowel\b',
        r'\bgamcha\b', r'\bmug\b', r'\blota\b', r'\bbucket\b', r'\bmugs\b', r'\bcomb\b', r'\bchiki\b',
        r'\bhair pin\b', r'\brubber band\b', r'\belastic\b', r'\brazor\b', r'\bblade\b', r'\bshave\b',
        r'\bshaving cream\b', r'\baftershave\b', r'\bdeodorant\b', r'\bdeo\b', r'\bperfume\b', r'\battar\b',
        r'\btissue\b', r'\btissue paper\b', r'\btoilet paper\b', r'\bbaby wipes\b', r'\bdiaper\b', r'\bnappy\b',
        r'\bpamper\b', r'\bhandset\b', r'\bandroid\b', r'\bsamsung\b', r'\bxiaomi\b', r'\bsymphony\b',
        r'\bwalton\b', r'\bcharger\b', r'\badapter\b', r'\bpower bank\b', r'\bUSB cable\b', r'\bdata cable\b',
        r'\bSIM card\b', r'\bmemory card\b', r'\bpen drive\b', r'\bflash drive\b', r'\bhard drive\b',
        r'\blaptop\b', r'\bdesktop\b', r'\bcomputer\b', r'\bPC\b', r'\bmonitor\b', r'\bkeyboard\b',
        r'\bmouse\b', r'\bprinter\b', r'\bscanner\b', r'\bphotocopy machine\b', r'\bxerox machine\b',
        r'\bxerox\b', r'\bphotostat\b', r'\bprojector\b', r'\bmultimedia projector\b', r'\bspeaker\b',
        r'\bheadphone\b', r'\bheadset\b', r'\bearphone\b', r'\bairpod\b', r'\bbluetooth\b', r'\bTV\b',
        r'\btelevision\b', r'\bLED TV\b', r'\bLCD TV\b', r'\bcable TV\b', r'\bDTH\b', r'\bremote\b',
        r'\bremote control\b', r'\bfan\b', r'\blight\b', r'\bLED bulb\b', r'\benergy saving bulb\b',
        r'\btube light\b', r'\bemergency light\b', r'\bpen\b', r'\bmatador\b', r'\becono\b', r'\bgel pen\b',
        r'\bballpoint pen\b', r'\bink pen\b', r'\bmarker\b', r'\bhighlighter\b', r'\bpencil\b',
        r'\bdiamond pencil\b', r'\beraser\b', r'\brubber\b', r'\bsharpener\b', r'\bruler\b', r'\bscale\b',
        r'\bcompass\b', r'\bgeometry box\b', r'\bnotebook\b', r'\bkhata\b', r'\bexercise book\b',
        r'\bclipboard\b', r'\bphotocopy paper\b', r'\bstapler\b', r'\bstaples\b', r'\bpin\b',
        r'\bdrawing pin\b', r'\bthumbtack\b', r'\bpaper clip\b', r'\bbinder clip\b', r'\bfile cover\b',
        r'\bclear file\b', r'\bplastic folder\b', r'\badhesive tape\b', r'\bcellotape\b', r'\bscotch tape\b',
        r'\bglue\b', r'\bfevicol\b', r'\bgum\b', r'\bcalculator\b', r'\bcalculator watch\b', r'\bcalendar\b',
        r'\bdiary\b', r'\bplanner\b', r'\bchula\b', r'\bblender\b', r'\bgrinder\b', r'\bjharu\b', r'\bbroom\b',
        r'\bmop\b', r'\bbucket\b', r'\btub\b', r'\bdetergent\b', r'\bsoap powder\b', r'\bwashing powder\b',
        r'\bwheel\b', r'\bcleaner\b', r'\btissue\b', r'\bcloth\b', r'\brag\b', r'\bkharika\b', r'\bscrubber\b',
        r'\bbrush\b', r'\btoilet brush\b', r'\bharpic\b', r'\blizol\b', r'\bphenyl\b', r'\bmosquito coil\b',
        r'\bmat\b', r'\ball out\b', r'\bhit\b', r'\bsandwich maker\b', r'\belectric kettle\b', r'\brice cooker\b',
        r'\bpressure cooker\b', r'\bfridge\b', r'\bfreezer\b', r'\bdeep freezer\b', r'\bwater purifier\b',
        r'\bfilter\b', r'\bdispenser\b', r'\bhammer\b', r'\bhathuri\b', r'\bscrewdriver\b', r'\bpliers\b',
        r'\bscissors\b', r'\bkainchi\b', r'\bknife\b', r'\bchaku\b', r'\bblade\b', r'\bnail\b', r'\bscrew\b',
        r'\bnut-bolt\b', r'\bwrench\b', r'\bspanner\b', r'\bdrill machine\b', r'\bcutter\b', r'\bmeasuring tape\b',
        r'\bscale\b', r'\blevel\b', r'\bladder\b', r'\blorry\b', r'\bmicrobus\b', r'\bCNG\b', r'\bcng\b',
        r'\bCNG auto-rickshaw\b', r'\bauto-rickshaw\b', r'\btempo\b', r'\blegged van\b', r'\brickshaw\b',
        r'\bbaby taxi\b', r'\btaxi\b', r'\btaxi cab\b', r'\bUber\b', r'\bPathao\b', r'\bbike\b', r'\bmotorbike\b',
        r'\bmotorcycle\b', r'\bscooter\b', r'\bcycle\b', r'\blaunch\b', r'\bsteamer\b', r'\bboat\b', r'\bnouka\b',
        r'\btrawler\b', r'\bspeedboat\b', r'\bhelicopter\b', r'\bgoli\b', r'\bmotorway\b', r'\bflyover\b',
        r'\bbridge\b', r'\bculvert\b', r'\bfootpath\b', r'\bpavement\b', r'\bfoot overbridge\b', r'\bzebra crossing\b',
        r'\btruck stand\b', r'\blaunch ghat\b', r'\bbus stand\b', r'\bdokan\b', r'\bstall\b', r'\bbazaar\b',
        r'\bbazar\b', r'\bmarket\b', r'\bsuper shop\b', r'\bsupermarket\b', r'\bshopping mall\b', r'\bmall\b',
        r'\bdepartment store\b', r'\bpharmacy\b', r'\bchemist\b', r'\bdrugstore\b', r'\bmedicine shop\b',
        r'\bdispensary\b', r'\bdoctor\'s chamber\b', r'\bclinic\b', r'\bhospital\b', r'\bdiagnostic center\b',
        r'\blaboratory\b', r'\bbank\b', r'\bATM\b', r'\bATM booth\b', r'\bpost office\b', r'\bcourier service\b',
        r'\bSundarban\b', r'\bSA Paribahan\b', r'\bPathao\b', r'\bfoodpanda\b', r'\bschool\b', r'\bcollege\b',
        r'\buniversity\b', r'\bcoaching center\b', r'\blibrary\b', r'\breading room\b', r'\bpark\b',
        r'\bplayground\b', r'\bfield\b', r'\bmaidan\b', r'\bmosque\b', r'\bmasjid\b', r'\btemple\b',
        r'\bmondir\b', r'\bpagoda\b', r'\beidgah\b', r'\bgraveyard\b', r'\bkoborsthan\b', r'\btaka\b',
        r'\bTK\b', r'\btk\b', r'\bpoisha\b', r'\bcash\b', r'\bchange\b', r'\bnote\b', r'\bbanknote\b',
        r'\bcoin\b', r'\bmobile banking\b', r'\bbKash\b', r'\bNagad\b', r'\bRocket\b', r'\bcredit card\b',
        r'\bdebit card\b', r'\bcard\b', r'\bcheque\b', r'\bcheck\b', r'\bdemand draft\b', r'\bpay order\b',
        r'\bwallet\b', r'\bpan\b', r'\bsupari\b', r'\bzorda\b', r'\bgul\b', r'\bkhili\b', r'\bbidi\b',
        r'\bsada\b', r'\bmeetha\b', r'\bshada\b', r'\bcharpoy\b', r'\bmachrari\b', r'\bpitari\b', r'\bkula\b',
        r'\bdheki\b', r'\bhata\b', r'\bkolshi\b', r'\bglassh\b', r'\bbati\b', r'\bprodip\b', r'\bpeRikane\b',
        r'\bhajek\b', r'\battor\b', r'\bshika\b', r'\bpithari\b', r'\bdala\b', r'\bchatai\b', r'\bmadur\b',
        r'\bhotna\b', r'\bpiri\b', r'\bchouki\b', r'\btakpo\b', r'\bbashi\b', r'\bpat\b', r'\bsal\b',
        r'\bchuri\b', r'\blaksha\b', r'\btaabiz\b', r'\bkanta\b', r'\bnakshi katha\b', r'\balu\b', r'\bholud\b',
        r'\bgaye holud\b', r'\bmehendi\b', r'\bhenna\b', r'\batta\b', r'\bchandan\b', r'\bshindur\b',
        r'\bnoa\b', r'\bshankha\b', r'\bpola\b', r'\bmistri\b', r'\belectric mistri\b', r'\bkamar\b',
        r'\bkumar\b', r'\bdhobai\b', r'\bnapit\b', r'\bdurai\b', r'\bostad\b', r'\bfootball\b', r'\bcricket\b',
        r'\bha-du-du\b', r'\bkabaddi\b', r'\bludo\b', r'\bcarrom\b', r'\bchess\b', r'\bdaba\b',
        r'\bplaying cards\b', r'\bmarble\b', r'\bguli\b', r'\bkite\b', r'\bghuri\b', r'\blatim\b',
        r'\bkanamachi\b', r'\bbouchi\b', r'\bgollachhut\b', r'\bdariabandha\b', r'\bekka-dokka\b', r'\bshowndh\b'
    ],
    'food': [
        r'\bvat\b', r'\bbhat\b', r'\bmach\b', r'\bmachh\b', r'\bdaal\b', r'\bdal\b',
        r'\bdoi\b', r'\brosogolla\b', r'\broshogolla\b', r'\bchomchom\b', r'\bphuchka\b',
        r'\bfuchka\b', r'\bchotpoti\b', r'\bsingara\b', r'\bsamucha\b', r'\bbakorkhani\b',
        r'\bbakarkhani\b', r'\bparatha\b', r'\bluchi\b', r'\bhilsa\b', r'\bilish\b',
        r'\bpanta ilish\b', r'\bpanta bhat\b', r'\bchira\b', r'\bmuri\b', r'\bcha\b',
        r'\bkacchi biryani\b', r'\bchicken chaap\b', r'\bkala bhuna\b', r'\brezala\b',
        r'\bpanta bhat\b', r'\bpanta ilish\b', r'\bshorshe ilish\b', r'\bchital macher muitha\b',
        r'\bdoi fuchka\b', r'\bfuska\b', r'\bbakarkhani\b', r'\bsondesh\b', r'\bkalojam\b',
        r'\bamriti\b', r'\blangcha\b', r'\bbiryani\b',
    ],
    'clothing': [
        r'\bsharee\b', r'\bsari\b', r'\bsaree\b', r'\bsalwar kameez\b', r'\bshalwar kameez\b',
        r'\bkameez\b', r'\bpanjabi\b', r'\bpunjabi\b', r'\bfatua\b', r'\bfatuas\b',
        r'\blungi\b', r'\bgamcha\b', r'\borkni\b', r'\bdupatta\b', r'\bchuridar\b',
        r'\bthree-piece\b', r'\bthree piece\b', r'\btant\b', r'\bjamdani\b', r'\btangail\b',
        r'\bnakshi kantha\b', r'\bthami\b', r'\bchad\b', r'\bkhadi\b', r'\bmuslin\b',
        r'\bzardozi\b',        # Metal embroidery (zari work)
        r'\bgotta-patti\b',    # Ribbon/lace embroidery
        r'\bkarchupi\b',       # Intricate embroidery (also written as karchobi/karchupi)
        r'\bkhadi\b',           #  handspun fabric
        r'\btant cotton\b',     # traditional Bengali cotton
        r'\bvoile\b',           # Lightweight fabric
        r'\bendi\b'            # eri silk
    ],
    'business_places': [
        r'\bDOHS\b', r'\bMohakhali\b', r'\bDhanmondi\b', r'\bGulshan\b', r'\bBanani\b',
        r'\bKarwan Bazar\b', r'\bCollege Street\b', r'\bDhaka College\b', r'\bUAE market\b',
        r'\bDhanmondi Rd\.?2\b', r'\bDhaka Sheraton\b', r'\bSheraton Hotel\b', r'\bNew Market\b',
        r'\bGausia\b', r'\bChawkbazar\b', r'\bSadarghat\b', r'\bShahbagh\b', r'\bFarmgate\b',
        r'\bMohammadpur\b', r'\bMirpur\b', r'\bUttara\b', r'\bbashundhara city\b', r'\bjatrabari\b',
        r'\bgabtoli\b', r'\bsayedabad\b', r'\bkamalapur\b', r'\bairport road\b', r'\bbaridhara\b',
        r'\bbashundhara\b', r'\bnikunja\b', r'\btejgaon\b', r'\bkazla\b', r'\bkallyanpur\b',
        r'\badabar\b', r'\bkazipara\b', r'\bshantinagar\b', r'\bmalibagh\b', r'\brajarbagh\b',
        r'\bramna\b', r'\bsegunbagicha\b', r'\bkakrail\b', r'\beskaton\b', r'\bpaltan\b',
        r'\bgulistan\b', r'\bdilkusha\b', r'\bnayapaltan\b', r'\bpurana paltan\b'
    ],
    'vocabulary': [
        r'\bfootball\b', r'\bpetrol\b', r'\bcinema hall\b', r'\bcinema halls\b',
        r'\bhall\b', r'\bhalls\b', r'\bpiccadilly\b', r'\bcantonment\b', r'\bbazaar\b',
        r'\bbazar\b', r'\bchai\b', r'\bpaan\b', r'\bautorickshaw\b', r'\brickshaw\b',
        r'\bcng\b', r'\bcurry\b', r'\bmasala\b', r'\bghee\b', r'\bpulao\b', r'\bpilaf\b',
        r'\bbiryani\b', r'\bchowk\b', r'\bmaidan\b', r'\bghat\b', r'\bmandir\b', r'\bmasjid\b',
        r'\bEidgah\b', r'\bmazar\b', r'\bhoohaas\b', r'\bthird wheeler\b',
        r'\bmiss calls\b',    # missed calls (common in BD mobile culture)
        r'\bstay-in soaps\b', # underarm deodorant soap
    ],
'echo_pairs': [
    r'\blaughs and giggles\b',
    r'\bpots and pans\b',
    r'\bglass, pots and pans\b',
    ],

    'idioms': [
        r'\bwhat is your good name\b', r'\bgood name\b', r'\bdo the needful\b',
        r'\bdoing the needful\b', r'\bout of station\b', r'\bprepone\b', r'\bpreponed\b',
        r'\bwould be\b.*?\bobliged\b', r'\bkindly revert\b', r'\bup to mark\b',
        r'\bmy namesake\b', r'\bcousin brother\b', r'\bcousin sister\b', r'\bonly\b.*?\bnamesake\b',
        r'\btenure\b', r'\b power of resilience\b', r'\bdon\'t worry be happy\b', r'\bme neither\b',
        r'\bchobi mela\b', r'\bdrik\b', r'\bprojonmo chottor\b', r'\bagnikonthi\b',
        r'\brazakar er fashi chai\b', r'\bjoy bangla\b', r'\bbangabandhu\b', r'\bmuktijoddha\b',
        r'\bmuktijoddhas\b', r'\boperation searchlight\b',
        r'\bfeather in (?:my|his|her|their) cap\b'
    ],
# Distinctive to Bangladeshi English
'bd_specific': [
    r'\bsells like hot cake\b',           # Missing plural
    r'\bbreathe of fresh air\b',          # "breath" vs "breathe" confusion
    r'\bMem Shaheb\b',                    # Banglish honorific
    r'\bsmoke up (?:son|brother|bhai)\b', # Code-switching
    r'\bsplurging their gizzards\b',      # Unique BD colloquialism
    r'\bbalderdash and codswallop\b',     # British-derived but BD context
    r'\bknock off walls\b',               # Non-standard idiom
    r'\bstirred .+ inside out\b',         # Non-standard variation
    r'\bhappy as a duck\b'
],
'hypenated':[
    r'\bbitter-sweet\b', r'\bmatters-of-fact\b', r'\bon-off relationship\b',
    r'\bon-off\b', r'\bclear-cut\b', r'\bjust-teen\b'
]

}