"""
British English Dictionary
Contains spelling patterns, vocabulary, and phrases specific to British English
"""

BRITISH_PATTERNS = {
    'or_vs_our': [
        r'\bcolour\b', r'\bhonour\b', r'\bfavour\b', r'\blabour\b', r'\bhumour\b',
        r'\bneighbour\b', r'\bbehaviour\b', r'\bflavour\b', r'\bvalour\b', r'\bvapour\b'
    ],
    'er_vs_re': [
        r'\bcentre\b', r'\btheatre\b', r'\bmetre\b', r'\bfibre\b', r'\blitre\b',
        r'\btheatre\b', r'\bcalibre\b', r'\bcentimetre\b', r'\bkilometre\b', r'\bmillimetre\b'
    ],
    'simplified_consonants': [
        r'\btravelling\b', r'\bcancelled\b', r'\bmodelling\b', r'\blabelled\b', r'\btraveller\b',
        r'\bcounsellor\b', r'\bjewellery\b', r'\bprogramming\b', r'\bquilting\b', r'\bsignalling\b',
        r'\bfuelling\b', r'\bmarvellous\b', r'\bappetiser\b'
    ],
    'se_vs_ce': [
        r'\bdefence\b', r'\blicence\b', r'\boffence\b', r'\bpretence\b', r'\bvice\b',
        r'\bpractise\b'
    ],
    'og_vs_ogue': [
        r'\bcatalogue\b', r'\bdialogue\b', r'\bmonologue\b', r'\bprologue\b', r'\bepilogue\b',
        r'\bdecalogue\b', r'\btravelogue\b'
    ],
    'ze_vs_se': [
        r'\banalyse\b', r'\bcatalyse\b', r'\bparalyse\b', r'\brecognise\b', r'\borganise\b',
        r'\bauthorise\b', r'\bcapitalise\b', r'\bcriticise\b', r'\bemphasise\b', r'\bfinalise\b',
        r'\bharmonise\b', r'\bidealise\b', r'\bimmunise\b', r'\blegalise\b', r'\bmaximise\b',
        r'\bmemorise\b', r'\bminimise\b', r'\bmobilise\b', r'\bnormalise\b', r'\boptimise\b',
        r'\borganise\b', r'\bpopularise\b', r'\brealise\b', r'\brecognise\b', r'\breorganise\b',
        r'\bstabilise\b', r'\bstandardise\b', r'\bsymbolise\b', r'\bsynchronise\b', r'\butilise\b',
        r'\bstigmatise\b', r'\bstigmatises\b'
    ],
    'got_vs_gotten': [
        r'\bhave got\b', r'\bhas got\b', r'\bhad got\b'
    ],
    'prepositions': [
        r'\bin a team\b', r'\bin the team\b', r'\bat the weekend\b',
        r'\bdifferent from\b', r'\bdifferent to\b', r'\bprotest against something\b'
    ],
    'articles': [
        r'\bin hospital\b', r'\bat university\b', r'\bat school\b',
        r'\bI\'ll see you on Monday\b', r'\bSee you on Tuesday\b', r'\bI\'ll call you on Friday\b',
        r'\bgo to university\b', r'\bgo to hospital\b'
    ],
    'collective_nouns': [
        r'\bthe team are\b', r'\bthe government have\b', r'\bthe company are\b',
        r'\bthe family are\b', r'\bthe staff are\b', r'\bthe committee are\b',
        r'\bthe class are\b', r'\bthe board are\b', r'\bthe group are\b',
        r'\bthe audience were\b', r'\bthe band are\b', r'\bthe crew have\b',
        r'\bthe board meet\b', r'\bthe couple have\b', r'\bthe population are\b',
        r'\bthe public are\b', r'\bthe press were\b', r'\bthe team were\b',
        r'\bthe family were\b', r'\bthe committee were\b', r'\bthe company were\b',
        r'\bthe group were\b'
    ],
    'everyday_objects': [
        r'\bflat\b', r'\blorry\b', r'\bbiscuit\b', r'\blift\b', r'\btorch\b',
        r'\bchips\b', r'\bpetrol\b', r'\bpavement\b', r'\bfootball\b',
        r'\bjumper\b', r'\bcrisps\b', r'\bbin\b', r'\bchemist\b', r'\bpram\b',
        r'\bnappy\b', r'\btap\b', r'\bboot\b', r'\bbonnet\b', r'\bpostbox\b',
        r'\baubergine\b', r'\bcourgette\b', r'\bdummy\b', r'\bsolicitor\b',
        r'\bflannel\b', r'\bduvet\b', r'\bwardrobe\b', r'\bgarden\b',
        r'\bcooker\b', r'\bgrill\b', r'\btrolley\b', r'\btrainers\b',
        r'\brubber\b', r'\bzip\b', r'\bsellotape\b', r'\bmobile phone\b',
        r'\bmobile\b', r'\bplaster\b', r'\bholiday\b', r'\bpost\b',
        r'\bcheque\b', r'\bcar park\b', r'\bmaths\b', r'\bpants\b',
        r'\btrousers\b', r'\bshop\b'
    ],
    'fashion_fitness': [
        r'\bexercising\b', r'\bvery busy\b', r'\bconsecutive meetings\b',
        r'\bpay a lot\b', r'\bspend a lot\b', r'\bjoggers\b',
        r'\btracksuit bottoms\b', r'\bwicking\b', r'\btights\b',
        r'\bvests\b', r'\bsleeveless tops\b', r'\btrainers\b',
        r'\bunderwear\b', r'\bknickers\b', r'\bhandbags?\b',
        r'\btracksuit\b', r'\bathleisure\b', r'\bactivewear\b'
    ],
    'business_lifestyle': [
        r'\bvery busy\b', r'\bback to back\b', r'\bpay a lot\b',
        r'\bZoom calls\b', r'\bZoom meetings\b', r'\bexercising\b',
        r'\bgame changer\b', r'\bhair regrowth treatment\b', r'\bmicro-needling\b',
        r'\bcv\b', r'\bplacement\b', r'\bmanaging director\b', r'\bredundancy\b',
        r'\bsacked\b', r'\bpay rise\b', r'\bpension\b', r'\bprivate health insurance\b',
        r'\bannual leave\b', r'\bsick pay\b', r'\bmaternity pay\b',
        r'\bwork from home\b', r'\bremote working\b', r'\bnappy\b',
        r'\bpram\b', r'\bdummy\b', r'\btap\b', r'\bchemist\b',
        r'\bplaster\b', r'\bcotton bud\b', r'\bkitchen roll\b',
        r'\bserviette\b', r'\btissue\b', r'\bloo roll\b', r'\bwashing up\b',
        r'\bwashing machine\b', r'\btumble dryer\b', r'\bhoover\b',
        r'\bmum\b', r'\bmummy\b', r'\bnan\b', r'\bnanna\b', r'\bgrandad\b',
        r'\bgreat nan\b', r'\bstay-at-home mum\b', r'\bworking mum\b',
        r'\btrousers\b', r'\bjumper\b', r'\btrainers\b', r'\bwaistcoat\b',
        r'\bvest\b', r'\btrackies\b', r'\bbumbag\b', r'\btights\b',
        r'\btracksuit\b', r'\bponytail\b', r'\bvests\b', r'\bsleeveless tops\b',
        r'\bwicking\b', r'\bexercising\b', r'\bworkout\b', r'\bjoggers\b',
        r'\bpound\b', r'\bquid\b', r'\bcheque\b', r'\bcurrent account\b',
        r'\bsavings account\b', r'\bcredit card\b', r'\bdebit card\b',
        r'\bstudent loan\b', r'\bmortgage\b', r'\brent\b', r'\bbills\b',
        r'\bfootball\b', r'\bamerican football\b', r'\brounders\b',
        r'\bnetball\b', r'\bbasketball\b', r'\bhockey\b', r'\bpitch\b',
        r'\bleisure centre\b', r'\bgym\b', r'\bworkout\b', r'\bexercising\b',
        r'\bfitness\b', r'\bpersonal trainer\b', r'\bGP\b',
        r'\bgeneral practitioner\b', r'\bA&E\b', r'\bcasualty\b',
        r'\bconsultant\b', r'\bpaediatrician\b', r'\bobstetrician\b',
        r'\bprivate medical insurance\b', r'\bprescription\b',
        r'\bover the counter\b', r'\bchemist\b', r'\bpharmacy\b',
        r'\bMonday to Friday\b', r'\bTuesday to Thursday\b',
        r'\bMonday through Friday\b', r'\bcommencing\b', r'\bat the weekend\b',
        r'\bat weekends\b', r'\bevery weekend\b', r'\bthis autumn\b',
        r'\blast autumn\b', r'\bnext autumn\b', r'\bdifferent to\b',
        r'\bdifferent from\b', r'\bprotest against\b', r'\bdemonstrate against\b',
        r'\bvisit\b', r'\bmeet\b', r'\btalk to\b', r'\bwrite to me\b',
        r'\bcall me\b', r'\btext me\b', r'\bI couldn\'t care less\b',
        r'\bin hospital\b', r'\bat university\b', r'\bat school\b',
        r'\bgo to hospital\b', r'\bgo to university\b', r'\bgo to school\b',
        r'\bhave got\b', r'\bhas got\b', r'\bhad got\b', r'\bhit the ground running\b',
        r'\bbite the bullet\b', r'\bcut to the chase\b',
        r'\btake it with a pinch of salt\b', r'\btouch wood\b',
        r'\bput a spanner in the works\b', r'\ba drop in the ocean\b',
        r'\bflogging a dead horse\b', r'\ba storm in a teacup\b',
        r'\bskeleton in the cupboard\b', r'\bsee the wood for the trees\b',
        r'\bblow one\'s own trumpet\b', r'\bthe ball is in your court\b',
        r'\bhit the nail on the head\b', r'\bunder the weather\b',
        r'\bonce in a blue moon\b', r'\bpiece of cake\b', r'\beasy as pie\b',
        r'\bcost an arm and a leg\b', r'\bburn the midnight oil\b',
        r'\bhit the books\b', r'\bface the music\b', r'\binstagram\b',
        r'\bfacebook\b', r'\btwitter\b', r'\bx\b', r'\btiktok\b',
        r'\bsnapchat\b', r'\bwhatsapp\b', r'\bzoom\b', r'\bDM\b',
        r'\bdirect message\b', r'\bpost\b', r'\bstory\b', r'\breel\b'
    ],
    'vocabulary': [
        r'\bfootball\b', r'\bpetrol\b', r'\bcinema\b', r'\bcinemas\b',
        r'\btheatre\b', r'\btheatres\b', r'\bbarracks\b', r'\bmarket\b',
        r'\btea\b', r'\btaxi\b', r'\btuk-tuk\b', r'\brice\b', r'\bspices\b',
        r'\bcurry\b', r'\bfried rice\b'
    ],
    'idioms': [
        r'\bwhat is your name\b', r'\bplease take necessary action\b',
        r'\bout of town\b', r'\bpostpone\b', r'\breschedule\b',
        r'\bthank you\b', r'\bplease reply\b', r'\bsatisfactory\b',
        r'\bmy namesake\b', r'\bcousin\b'
    ],
    'common_phrases': [
        r'\bwhat is your name\b', r'\bwhat is your full name\b',
        r'\bwhere are you from\b', r'\bwhere do you live\b',
        r'\bwhat city are you from\b', r'\bhow are you\b',
        r'\bhow are you doing\b', r'\byou alright\b', r'\balright\b',
        r'\bhow\'s it going\b', r'\bhow do you do\b', r'\bcheers\b',
        r'\bthank you\b', r'\bthanks\b', r'\bthank you very much\b',
        r'\bthanks very much\b', r'\byou\'re welcome\b', r'\bno problem\b',
        r'\bno worries\b', r'\bmy pleasure\b', r'\bwelcome\b',
        r'\bplease come in\b', r'\bcome in\b', r'\bhave a seat\b',
        r'\bplease sit down\b', r'\bwould you like some tea\b',
        r'\bfancy a cuppa\b', r'\bcup of tea\b', r'\bcoffee\b',
        r'\bsir\b', r'\bmadam\b', r'\bma\'am\b', r'\bmister\b',
        r'\bmr\b', r'\bmrs\b', r'\bms\b', r'\bmx\b', r'\byour honour\b',
        r'\bofficer\b', r'\bdoctor\b', r'\bdr\b', r'\bprofessor\b',
        r'\breverend\b', r'\bfather\b', r'\bvicar\b', r'\bpastor\b',
        r'\bbrother\b', r'\bsister\b', r'\blord\b', r'\blady\b',
        r'\bplease\b', r'\bplease do\b', r'\bplease let me know\b',
        r'\bplease respond\b', r'\bplease reply\b', r'\bplease advise\b',
        r'\bI would appreciate it if\b', r'\bI would be grateful if\b',
        r'\bI would be obliged if\b', r'\byour prompt response would be appreciated\b',
        r'\byour cooperation is appreciated\b', r'\bthank you for your cooperation\b',
        r'\bthis morning\b', r'\btonight\b', r'\blast night\b',
        r'\bday before yesterday\b', r'\bday after tomorrow\b',
        r'\bin the morning\b', r'\bin the afternoon\b', r'\bin the evening\b',
        r'\bat night\b', r'\bat noon\b', r'\bat midnight\b',
        r'\bhalf past eight\b', r'\bquarter to\b', r'\bquarter past\b',
        r'\bten past\b', r'\btwenty to\b', r'\bfive past\b',
        r'\btwenty past\b', r'\btwenty-five past\b', r'\btwenty-five to\b',
        r'\bwhat time is it\b', r'\bwhat\'s the time\b', r'\bo\'clock\b',
        r'\baround this time\b', r'\baround that time\b', r'\bI\'m going\b',
        r'\bI\'m off\b', r'\bI\'m coming\b', r'\bI\'m on my way\b',
        r'\bI\'ll be there\b', r'\bI\'ll come\b', r'\bI\'m from\b',
        r'\bI come from\b', r'\bwhat can I do\b', r'\bwhat can you do\b',
        r'\bwhat to say\b', r'\bwhat can I say\b', r'\bwhat can I tell you\b',
        r'\bbye\b', r'\bgoodbye\b', r'\bsee you\b', r'\bsee you later\b',
        r'\blater\b', r'\bcheerio\b', r'\bI\'ll see you\b', r'\bwe\'ll meet\b',
        r'\bwe\'ll catch up\b', r'\bwe\'ll get together\b', r'\bhave lunch\b',
        r'\bhave dinner\b', r'\bhave you eaten\b', r'\bdid you eat\b',
        r'\bhave you had your meal\b', r'\bI have just eaten\b',
        r'\bI have just finished\b', r'\bjust now\b', r'\bhe has just left\b',
        r'\bout of town\b', r'\baway\b', r'\bI\'ll be out of town\b',
        r'\bI\'ll be away\b', r'\bon holiday\b', r'\bon leave\b',
        r'\bI\'m off today\b', r'\bI\'m out today\b', r'\bannual leave\b',
        r'\bAL\b', r'\bsick leave\b', r'\bunpaid leave\b', r'\bfamily leave\b',
        r'\bmaternity leave\b', r'\bpaternity leave\b', r'\bleave application\b',
        r'\btime off request\b', r'\bhalf day\b', r'\boffer letter\b',
        r'\bemployment letter\b', r'\bpromotion letter\b', r'\breference letter\b',
        r'\brecommendation letter\b', r'\bproof of employment\b',
        r'\bsalary verification\b', r'\bNOC\b', r'\bNo Objection Certificate\b',
        r'\bcashing in\b', r'\bcashing out\b', r'\bcashing in annual leave\b',
        r'\bpension\b', r'\bpension scheme\b', r'\bworkplace pension\b',
        r'\bstate pension\b', r'\bprivate pension\b', r'\btax return\b',
        r'\bself-assessment\b', r'\bP60\b', r'\bP45\b', r'\bNI number\b',
        r'\bNational Insurance number\b', r'\bUTR\b', r'\bUnique Taxpayer Reference\b',
        r'\bwhat is your educational background\b', r'\bwhat qualifications do you have\b',
        r'\bwhat did you study\b', r'\bI graduated in 2010\b',
        r'\bI graduated from\b', r'\bI got my degree in\b', r'\bI studied at\b',
        r'\bI went to\b', r'\bmy degree\b', r'\bmy subject\b', r'\bA-levels\b',
        r'\bA-level\b', r'\bGCSEs\b', r'\bGCSE\b', r'\bNational 5\b',
        r'\bHighers\b', r'\bAdvanced Highers\b', r'\bbaccalaureate\b',
        r'\buniversity life\b', r'\bhalls of residence\b', r'\bhalls\b',
        r'\bstudent union\b', r'\bfreshers\b', r'\bfreshers week\b',
        r'\bmodule\b', r'\bcourse\b', r'\blecture\b', r'\bseminar\b',
        r'\btutorial\b', r'\boptional module\b', r'\bcore module\b',
        r'\bcompulsory module\b', r'\bprerequisite\b', r'\bI got a first\b',
        r'\bI got a 2:1\b', r'\bupper second\b', r'\bI got a 2:2\b',
        r'\blower second\b', r'\bI got a third\b', r'\bI got a distinction\b',
        r'\bI got a merit\b', r'\bI got a scholarship\b', r'\badmission test\b',
        r'\buniversity admission\b', r'\bUCAS\b', r'\bRussell Group\b',
        r'\bOxbridge\b', r'\bred brick university\b', r'\bnew university\b',
        r'\bmed school\b', r'\bmedical school\b', r'\blaw school\b',
        r'\bbusiness school\b'
    ],
    'verb_tenses': [
        r'\bI have just eaten\b', r'\bI have just finished\b', r'\bI have just seen\b',
        r'\bI have just come\b', r'\bI have just gone\b', r'\bI have just done it\b',
        r'\bI have just left\b', r'\bI have just arrived\b', r'\bI have just called\b',
        r'\bHe has just left\b', r'\bShe has just come\b', r'\bThey have just arrived\b',
        r'\bI have already eaten\b', r'\bI have already finished\b', r'\bI have already seen\b',
        r'\bI have already done it\b', r'\bI have already gone\b', r'\bI have already come\b',
        r'\bHave you eaten yet\?\b', r'\bHave you finished yet\?\b',
        r'\bHave you called yet\?\b', r'\bHave you gone yet\?\b',
        r'\bI have never seen that\b', r'\bI have never done that\b',
        r'\bI have never been there\b', r'\bI have never eaten that\b',
        r'\bHave you ever been\b', r'\bHave you ever seen\b',
        r'\bHave you ever tried\b', r'\bHave you ever eaten\b',
        r'\bI have just eaten\b', r'\bI have just finished\b',
        r'\bI have just seen\b', r'\bI have just come\b',
        r'\bI have been here since morning\b',
        r'\bI have been waiting for two hours\b',
        r'\bI have known him for five years\b',
        r'\bI have lived here since 2010\b',
        r'\bI had done it before he came\b',
        r'\bI had finished when he arrived\b',
        r'\bI had already eaten when he called\b',
        r'\bI will have finished by tomorrow\b',
        r'\bI will have completed it before you come\b',
        r'\bIf I had known\b', r'\bIf I had seen\b',
        r'\bIf I had gone\b', r'\bIf I had tried\b',
        r'\bI wouldn\'t have gone\b', r'\bI would have gone\b',
        r'\bHe wouldn\'t have come\b', r'\bHe would have come\b',
        r'\bI didn\'t go until he came\b',
        r'\bI won\'t leave until you come\b',
        r'\bIt has been two years since I met him\b',
        r'\bNo sooner did I arrive than he left\b',
        r'\bNo sooner had I arrived than he left\b',
        r'\bHardly had I arrived when he called\b',
        r'\bAs soon as I arrived, he left\b',
        r'\bWhile I was going, I met him\b',
        r'\bWhen I was coming, I saw her\b',
        r'\bBy the time I arrived, he had left\b',
        r'\bAfter I finished, I went home\b',
        r'\bBefore I left, I called him\b',
        r'\bSince I met you, my life has changed\b',
        r'\bI had already finished when he came\b',
        r'\bI had never seen such a thing\b',
        r'\bI am going tomorrow\b', r'\bHe is coming next week\b',
        r'\bThey are arriving tonight\b', r'\bWe are starting next month\b',
        r'\bWhen I was young, I would play cricket\b',
        r'\bI used to play football\b', r'\bHe used to live here\b',
        r'\bYou had better go\b', r'\bYou\'d better go\b',
        r'\bHe had better leave\b', r'\bHe\'d better leave\b',
        r'\bI would rather stay\b', r'\bI\'d rather stay\b',
        r'\bHe would rather go\b', r'\bHe\'d rather go\b',
        r'\bHe talks as if he knew everything\b',
        r'\bIt is time we left\b', r'\bIt\'s time we left\b',
        r'\bI wish I knew\b', r'\bI wish I were there\b',
        r'\bIf only I knew\b', r'\bThe work was done by me\b',
        r'\bThe letter was sent by him\b', r'\bI got the work done\b',
        r'\bHe had his car repaired\b', r'\bShe got her hair cut\b',
        r'\bHe kept on talking\b', r'\bShe kept on working\b',
        r'\bHe went on talking\b', r'\bHe stopped smoking\b',
        r'\bHe stopped to smoke\b', r'\bI remember meeting him\b',
        r'\bI remembered to meet him\b', r'\bI tried calling\b',
        r'\bI tried to call\b', r'\bThis means changing plans\b',
        r'\bI meant to change plans\b', r'\bI regret saying that\b',
        r'\bI regret to inform you\b', r'\bI am afraid of flying\b',
        r'\bI am afraid to fly\b', r'\bI am interested in learning\b',
        r'\bI am interested to learn\b', r'\bHe said that he would come\b',
        r'\bShe told me that she was coming\b', r'\bHe asked me what my name was\b',
        r'\bHe told me to go\b', r'\bShe ordered me to leave\b',
        r'\bLet\'s go\b', r'\bLet\'s eat\b', r'\bLet\'s start\b',
        r'\bLet me go\b', r'\bLet him try\b', r'\bMake him understand\b',
        r'\bMake her see\b', r'\bHave it done\b', r'\bHave it checked\b',
        r'\bGet it done\b', r'\bGet it fixed\b', r'\bIt needs cleaning\b',
        r'\bIt needs to be cleaned\b', r'\bI want it done\b',
        r'\bI want it finished\b', r'\bI saw him coming\b',
        r'\bI saw him come\b', r'\bHelp me do it\b',
        r'\bHelp me to do it\b', r'\bPrevent him from going\b',
        r'\bStop her from leaving\b', r'\bHe insisted on going\b',
        r'\bShe insisted on coming\b', r'\bHe apologised for being late\b',
        r'\bThank you for coming\b', r'\bThank you for helping\b',
        r'\bI look forward to meeting you\b',
        r'\bWe look forward to hearing from you\b', r'\bI used to smoke\b',
        r'\bI am used to smoking\b', r'\bI am about to leave\b',
        r'\bHe is about to start\b', r'\bI am going to go\b',
        r'\bI will go\b', r'\bI shall go\b', r'\bWe shall see\b',
        r'\bI shan\'t be long\b', r'\bShall I go\?\b',
        r'\bShall we start\?\b', r'\bMay I come in\?\b',
        r'\bMay I ask something\?\b', r'\bI might come\b',
        r'\bHe might be late\b', r'\bI can do it\b',
        r'\bCan I go\?\b', r'\bCould you help\?\b',
        r'\bCould I borrow this\?\b', r'\bYou should go\b',
        r'\bWe should help\b', r'\bYou must go\b', r'\bWe must help\b',
        r'\bI have to go\b', r'\bHe has to leave\b', r'\bI need to go\b',
        r'\bYou need to understand\b', r'\bYou ought to help\b',
        r'\bWe ought to respect our elders\b', r'\bI prefer to stay\b',
        r'\bI prefer staying\b', r'\bI like to read\b', r'\bI like reading\b',
        r'\bI love to travel\b', r'\bI love travelling\b',
        r'\bI hate to wait\b', r'\bI hate waiting\b', r'\bI started to work\b',
        r'\bI started working\b', r'\bI began to understand\b',
        r'\bI began understanding\b', r'\bI continued to work\b',
        r'\bI continued working\b'
    ],
'ence_vs_ense': [
    r'\bdefence\b', r'\boffence\b', r'\bpretence\b', r'\blicence\b'
    # US uses defense, offense, pretense, license
    ],
'past_irregulars': [
    r'\bleapt\b', r'\bdreamt\b', r'\blearnt\b', r'\bspelt\b', r'\bspilt\b',
    r'\bburnt\b', r'\bknelt\b', r'\bwept\b', r'\bsmelt\b'
    # US often uses leaped, dreamed, learned, spelled, spilled, burned, kneeled
    ],
'consonant_doubling': [
    r'\bfocussed\b', r'\bfocussing\b', r'\bbias\b', r'\bbiassed\b',
    r'\bprogramme\b', r'\bprogramming\b',  # programme as noun
    r'\bkidnapper\b', r'\bworshipped\b'
    ],
'time_expressions': [
    r'\ba quarter past\b', r'\ba quarter to\b', r'\bhalf past\b',
    r'\bten to\b', r'\bfive past\b', r'\btwenty-five to\b',
    r'\bMonday week\b', r'\ba week on Monday\b',  # "I'll see you Monday week"
    r'\bfortnight\b', r'\bfortnightly\b'
    ],
'modal_expressions': [
    r'\bshan\'t\b',  # shall not
    r'\bmightn\'t\b',  # might not
    r'\bneedn\'t\b',  # need not
    r'\bdaren\'t\b',  # dare not
    r'\boughtn\'t\b',  # ought not
    r'\bhaving said that\b',
    r'\bat the end of the day\b',
    r'\bto be fair\b',
    r'\bmind you\b',
    r'\bfair enough\b'
    ],
'mild_expletives': [
    r'\bbloody\b', r'\bbugger\b', r'\bblimey\b', r'\bcor\b',
    r'\bbollocks\b', r'\btosser\b', r'\bgit\b', r'\bplonker\b'
    ],
'hyphenated': [
    r'\blower-class\b', r'\bworking-class\b', r'\bmiddle-class\b',
    r'\bstate-school\b', r'\bpublic-school\b'  # means private school in UK!
    ],
'false_friends': [
    r'\bbiscuit\b',  # UK: cookie-like; US: savory scone
    r'\bjumper\b',   # UK: sweater; US: someone who jumps
    r'\bpants\b',    # UK: underwear; US: trousers
    r'\bboot\b',     # UK: car trunk; US: footwear
    ]
}